NationalBankBelgium/stark

starter/src/app/app.module.ts

The PreloadingAllModules strategy caused all the modules (including the lazy-loaded) to be preloaded when the application loads (see: https://angular.io/guide/router#how-preloading-works)

fix(starter): remove PreloadAllModules preloading strategy from routing configuration to make lazy-loaded modules to be actually lazy loaded :)

---

starter/package.json
starter/src/polyfills.browser.ts

- add needed npm dependencies for those polyfils
- remove obsolete polyfills for deprecated pipes since Angular 5
- remove ie-shim package since it is to be used only for IE9

feat(polyfills): update polyfills to leave only those relevant for IE11 and some special features from Angular

---

CONTRIBUTING.md

```
[ ] Bugfix
[ ] Feature
```
Added commit message guidelines based on Angular's. Will allow us to use semantic-release and conventional-changelog

docs(commits): added rules for commit messages. closes #28

---

packages/rollup.config.common-data.js
packages/stark-build/config/build-utils.js
packages/stark-build/config/tslint.json
packages/stark-build/config/webpack.common.js
packages/stark-build/config/webpack.prod.js
packages/stark-core/package.json
packages/stark-core/src/http/http.module.ts
packages/stark-core/src/http/services/http.service.spec.ts
packages/stark-core/src/http/services/http.service.ts
packages/stark-core/src/logging/services/logging.service.spec.ts
packages/stark-core/src/test/unit-testing/unit-testing-utils.ts
starter/src/app/app.routes.ts
starter/src/app/home/home.component.ts

```
[ ] Bugfix
[ ] Feature
```
Prototype-patched based observables/operators are used in all our codebase due to this kind of imports:
```javascript
import "rxjs/add/observable/of";
import "rxjs/add/operator/foo";
import "rxjs/add/operator/baz";
```
Issue Number: #258 
Pipeable observables/operators are used now by doing this kind of imports:
```javascript
import { of } from "rxjs/observable/of";
import { foo } from "rxjs/operators/foo";
import { baz } from …
```

chore(rxjs): use pipeable operators instead of prototype-patched based operators

---

packages/stark-build/config/webpack.common.js
packages/stark-core/src/configuration/entities/application/app-config.entity.intf.ts
packages/stark-core/src/http/http.module.ts
packages/stark-core/src/logging/index.ts
packages/stark-core/src/logging/logging.module.ts
packages/stark-core/src/logging/services/logging.service.ts
starter/package.json
starter/src/app/+barrel/+child-barrel/child-barrel.component.ts
starter/src/app/+barrel/barrel.component.ts
starter/src/app/+detail/+child-detail/child-detail.component.ts
starter/src/app/+detail/detail.component.ts
starter/src/app/+dev-module/dev-module.component.ts
starter/src/app/about/about.component.spec.ts
starter/src/app/about/about.component.ts
starter/src/app/app.module.ts
starter/src/app/home/home.component.spec.ts
starter/src/app/home/home.component.ts

```
[ ] Bugfix
[x] Feature
```
Logging service not yet available in the Starter app.
Issue Number: #91
Logging service implemented in the Starter app.
Created a "STARK_APP_CONFIG" token to provide the StarkConfig from the client app into Stark.
```
[x] Yes
[ ] No
```
"STARK_APP_CONFIG" token has to be used to inject the AppConfig in components and services.

feat(logging): implement STARK_APP_CONFIG token and implement Stark logging in Starter

---

build-functions.sh

The build script displays now warning messages everytime a warning message is showed by Rollup, even when --trace argument is not passed.
Also, the build is now stopped when there is an error in during Rollup process.
```
[ ] Bugfix
[X] Feature
```
Issue Number: #278 
Throw an error when there is an error during rollup process.
```
[ ] Yes
[ ] No
```

feat(build) Trigger an error during build when rollup fails.

---

packages/stark-core/src/common/error/error.intf.ts
packages/stark-core/src/common/error/error.ts
packages/stark-core/src/common/error/index.ts
packages/stark-core/src/common/index.ts
packages/stark-core/src/http/entities/error/http-error-base.entity.intf.ts
packages/stark-core/src/http/entities/error/http-error-base.entity.ts
packages/stark-core/src/http/entities/error/http-error-detail.entity.ts
packages/stark-core/src/http/entities/error/http-error-wrapper.entity.ts
packages/stark-core/src/http/entities/error/http-error.entity.ts
packages/stark-core/src/http/services/http.service.spec.ts
packages/stark-core/src/http/services/http.service.ts
packages/stark-core/src/logging/entities/log-message.entity.intf.ts
packages/stark-core/src/logging/entities/log-message.entity.ts
packages/stark-core/src/logging/entities/logging.entity.ts
packages/stark-core/src/logging/services/logging.service.intf.ts
packages/stark-core/src/logging/services/logging.service.spec.ts
packages/stark-core/src/logging/services/logging.service.ts
packages/stark-core/src/stark-core.ts
packages/stark-core/src/user/services/user.service.spec.ts
starter/package.json
starter/src/app/home/home.component.html
starter/src/app/home/home.component.ts

```
[ ] Bugfix
[x] Feature
```
The Error object only provides a message.
When logging errors, a cast is needed for other types of errors, like for instance the HttpError
Issue Number: #96
The Error object provides: message, name (=error type) , timestamp, correlationId and stack information.
HTTP errors extend the StarkError object.
The logging service accepts Error objects and all error objects that extend the StarkError.
The logging service provides more information. …

feature(error): implement StarkError classes and adapt http and logging service

---

packages/stark-core/karma.conf.typescript.ci.js
packages/stark-core/src/configuration/entities/application/app-config.entity.ts
packages/stark-core/src/configuration/entities/language/language.entity.ts
packages/stark-core/src/http/services/http.service.spec.ts
packages/stark-core/src/logging/services/logging.service.spec.ts
packages/stark-core/src/routing/services/routing.service.spec.ts
packages/stark-core/src/session/services/session.service.spec.ts
packages/stark-core/src/session/services/session.service.ts
packages/stark-core/src/user/services/user.service.spec.ts
packages/stark-core/src/validation/decorators/is-bban/is-bban.validator.decorator.ts
packages/stark-core/src/validation/decorators/is-bic/is-bic.validator.decorator.ts
packages/stark-core/src/validation/decorators/is-company-number/is-company-number.validator.decorator.ts
packages/stark-core/src/validation/decorators/is-establishment-unit-number/is-establishment-unit-number.validator.decorator.ts
packages/stark-core/src/validation/decorators/is-iban/is-iban.validator.decorator.ts
packages/stark-core/src/validation/decorators/is-isin/is-isin.validator.decorator.ts
packages/stark-core/src/validation/decorators/is-kbo/is-kbo.validator.decorator.ts
packages/stark-core/src/validation/decorators/is-nin/is-nin.validator.decorator.ts
packages/stark-core/src/validation/decorators/is-supported-language/is-supported-language.validator.decorator.ts
packages/stark-core/src/validation/decorators/map-is-valid/map-is-valid.validator.decorator.ts
packages/stark-core/src/validation/decorators/map-not-empty/map-not-empty.validator.decorator.ts
starter/src/app/app.module.ts

```
[X] Bugfix
[ ] Feature
```
- Stark validator decorators not yet used where they used to be.
- NGC throws an exception due to an issue while handling re-exports (see angular/angular#20931)
- StarkAppMetadata not used in Starter
Stark validator decorators and StarkAppMetadata are now used. A workaround is implemented to avoid the NGC compilation error (until it is fixed)
```
[ ] Yes
[X] No
```

fix(core): fix ngc issues and clean-up code in stark-core. Integrate AppMetadata in Starter

---

.prettierignore
starter/.prettierignore

```
[X] Bugfix
[ ] Feature
```
Prettier takes a useless long time on package-lock.json files and analyzes coverage and reports folder which are ignored by git.
Those files/folders are ignored by Prettier
```
[ ] Yes
[X] No
```

fix(prettier) Add package-lock.json, coverage and reports folder to prettier ignored files

---

.cz-config.js
CONTRIBUTING.md
commitlint.config.js
package.json

```
[ ] Bugfix
[x] Feature
```
Issue Number: #290 
- Add [Commitizen](https://github.com/commitizen/cz-cli) and [Commitlint](https://github.com/marionebl/commitlint) to help us standardize out commit messages.
- Add dependencies, scripts in package.json of the root
- Add doc in CONTRIBUTING.md
- Add configuration in root :
.cz-config.js (config for customizable template for `Commitizen`)
commitlint.config.js (config for `Commitlint`)
```
[ ] Yes
[x] No
```

feat(stark-all): add commitizen + commitlint with scripts, config & dependencies

---

packages/stark-build/config/webpack.dev.js
packages/stark-build/package.json

ISSUES CLOSED: #322
```
[ ] Bugfix
[x] Feature
```
Issue Number: #322
Add webpackMonitor to the build.
The reports for it will be generated in starter/reports/webpack-monitor/stats.json
```
[ ] Yes
[x] No
```

feat(build): add webpackMonitor

---

packages/stark-build/config/webpack.common-data.js
packages/stark-build/config/webpack.common.js
packages/stark-build/config/webpack.dev.js
packages/stark-build/config/webpack.prod.js
packages/stark-build/config/webpack.test.js
packages/stark-build/package.json
starter/.angular-cli.json
starter/src/index.html

ISSUES CLOSED: #148
```
[ ] Bugfix
[X] Feature
```
The URL of the CSS resources is not correctly updated when the deploy url and/or the base href defined in the angular-cli.json is customized.
Issue Number: #148 
The base url can be customized now via the baseHref option of angular-cli.json.
The deploy URL defined in the deployUrl option of angular-cli.json is correctly appended to the CSS resources thanks to the custom configuration taken from Angular CLI.
```
[X] Yes …
```

feat(build): add support for custom baseHref and deployUrl in angular-cli.json file with BaseHrefWebpackPlugin

---

starter/src/app/app.module.ts
starter/src/stark-app-config.json

ISSUES CLOSED: #261 
```
[ ] Bugfix
[X] Feature
```
NgIdleKeepAlive not imported in the App module of the Starter.
Issue Number: #261 
NgIdleAlive is imported now in the App module although it is not enabled by the moment (keepAliveDisabled: true) until `json-server` is integrated in the Starter
```
[ ] Yes
[X] No
```

feat(stark-starter): add NgIdleKeepAlive module in app module

---

packages/stark-build/config/webpack.common.js
packages/stark-build/config/webpack.dev.js
packages/stark-build/config/webpack.prod.js
packages/stark-build/config/webpack.test.js

```
[X] Bugfix
[ ] Feature
```
SASS and SCSS files are not correctly processed by Webpack causing the custom styles for Angular Material components and themes to be broken.
Issue Number: #104
Custom styles for Angular Material components and themes working properly.
```
[ ] Yes
[X] No
```

fix(stark-build): include postcss loader+plugins to the Webpack css and scss files processing

---

.prettierignore
CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md
RELEASE.md
SNAPSHOTS.md
docs/COMMON_DEV_ERRORS.md
docs/PRETTIER.md
docs/WEBPACK.md
package.json
packages/README.md
packages/stark-build/config/README.md
packages/stark-core/src/common/translations/translations.spec.ts
packages/stark-core/src/modules/http/repository/http-abstract-repository.spec.ts
packages/stark-core/src/modules/routing/actions/routing.actions.ts
packages/stark-core/src/modules/routing/services/routing.service.spec.ts
packages/stark-core/src/modules/routing/services/routing.service.ts
packages/stark-core/src/modules/session/actions/session.actions.ts
packages/stark-core/src/modules/settings/actions/settings.actions.ts
packages/stark-core/src/validation/validators/is-company-number/is-company-number.validator.fn.ts
showcase/README.md
starter/README.md
starter/src/app/about/about.component.spec.ts

```
[ ] Bugfix
[ ] Feature
```
Formatting applied using a previous version of Prettier. MD files were not included in the set of files to be auto-formatted.
Re-format files using the latest version of Prettier. MD files also auto-formatted.
**Important: the CHANGELOG.md file is excluded from this auto-formatting because it is auto-generated on every release!**
```
[ ] Yes
[X] No
```

style(stark-all): re-format files with latest Prettier version. Include MD files in Prettier auto formatting.

---

packages/stark-core/src/common.ts
packages/stark-core/src/common/translations.ts
showcase/src/app/translation.config.ts
starter/src/app/translation.config.ts

```
[ ] Bugfix
[ ] Feature
```
Wrong imports in Starter and Showcase for common translation utils/classes from `stark-core`:
```
import { mergeTranslations } from "../../../packages/stark-core/src/common/translations/translations";
import { StarkLocale } from "../../../packages/stark-core/src/common/translations/locale.intf";
```
Imports fixed:
```
import { mergeTranslations, StarkLocale } from "@nationalbankbelgium/stark-core";
```
```
[ ] Yes
[X] No
```

fix(stark-core): add missing barrel for common/translations folder. Fix stark-core translations utils imports.

---

docs/ENVIRONMENTS.md

```
[ ] Bugfix
[ ] Feature
```
No documentation existed about the way to find out the current environment within Stark applications. 
Documentation has been added to help developers. 
```
[ ] Yes
[x] No

docs(build): documented environment support

---

packages/stark-build/config/tslint.json
packages/stark-core/tslint.json
packages/stark-ui/src/modules.ts
packages/stark-ui/src/modules/app-logo/components/app-logo.component.ts
packages/stark-ui/src/modules/svg-view-box.ts
packages/stark-ui/src/modules/svg-view-box/directives.ts
packages/stark-ui/src/modules/svg-view-box/directives/svg-view-box.directive.spec.ts
packages/stark-ui/src/modules/svg-view-box/directives/svg-view-box.directive.ts
packages/stark-ui/src/modules/svg-view-box/svg-view-box.module.ts
packages/stark-ui/tslint.json

ISSUES CLOSED: #455
```
[X] Bugfix
[X] Feature
```
Issue Number: #455 
The new `StarkSvgViewBoxDirective` directive is included in the new `StarkSvgViewBoxModule` so it should be imported in the AppModule:
```typescript
@NgModule({
bootstrap: [AppComponent],
declarations: [AppComponent],
imports: [
...
MatIconModule,  // needed by the mat-icon directive
StarkSvgViewBoxModule
],
providers: [ ... ]
})
export class AppModule { }
```
The directive should be used together …

feat(stark-ui): implement SvgViewBox directive to enable resizing of Angular Material's mat-icon directive

---

packages/stark-build/config/build-utils.js
showcase/angular.json
showcase/src/environments/environment.e2e.prod.ts
showcase/src/environments/environment.hmr.ts
showcase/src/environments/environment.prod.ts
showcase/src/environments/environment.ts

```
[X] Bugfix
[ ] Feature
```
Issue Number: #466 
The base href of the showcase is set dynamically via the Angular [APP_BASE_HREF](https://angular.io/api/common/APP_BASE_HREF) provider as an environment provider instead of setting it in the `angular.json` file in order to handle the final location of the app in GitHub pages (defined in `environment.prod.ts`).
The handling of the environment files in Webpack is works correctly now due to some minor fixes in the …

fix(stark-demo): add baseHref dynamically via Angular provider to fix Showcase when published in GitHub pages

---

.travis.yml
gh-deploy.sh
package.json
showcase/ghpages-adapt-angular-json.js
showcase/ghpages-adapt-bundle-urls.js
showcase/package.json
showcase/src/environments/environment.e2e.prod.ts
showcase/src/environments/environment.hmr.ts
showcase/src/environments/environment.prod.ts
showcase/src/environments/environment.ts

ISSUES CLOSED: 466
```
[X] Bugfix
[ ] Feature
```
Although the baseHref can be dynamically changed via the Angular APP_BASE_HREF provider, the CSS and other assets are imported from the wrong folder since the deployUrl is used during the bundle building by Wepack to generate such imports. The issue is that the deployUrl cannot be defined dynamically.
Issue Number: #466 
Reverted the changes made in #471 related to the definiton of the APP_BASE_HREF as an environment …

fix(stark-demo): revert PR #471. Adapt baseHref/deployUrl via Node script to fix Showcase publication on GitHub pages

---

greenkeeper.json

```
[X] Bugfix
[ ] Feature
```
The `package.json` files of the "testing" subpackages are included in the `greenkeeper.json` file. This seems to break greenkeeper which does not any create new PRs for updating deps in our repo.
The `greenkeeper.json` file contains only those `package.json` files from the packages that do have dependencies.
```
[ ] Yes
[X] No
```

chore(stark-all): remove "testing" subpackages from greenkeeper config file since they have no dependencies

---

build-functions.sh

```
[ ] Bugfix
[ ] Feature
```
When there is an empty coverage folder in a project, the `rollupIndex` function ends up in an infinite loop.
The `coverage` folder is added to the 'Ignored Directory' list.
```
[ ] Yes
[x] No
```

build(stark-all): exclude the 'coverage' folder from the build process

---

CONTRIBUTING.md

When building a subset of stark (ie: npm run build:stark-ui) on MacOS you might get the error:
```
sed: illegal option -- r
```
This is due to a difference in sed script on Windows OS and MacOS. On Windows the command is `sed -r ...` on MacOS this it is `sed -E ...` .
```
[ ] Bugfix
[ ] Feature
```
We have no solution for the `sed: illegal option -- r` error.
A solution is added to the 'contributing' document under 'if you only want to build a subset of stark'.
```
[ ] …
```

docs(docs): add solution for the 'sed: illegal option -- r' error when building a subset of stark

---

package.json

When running the `npm run prettier-check` command on MacOs not all files are checked by Prettier.
The solution is to add double quotes around the globs.
```
[x] Bugfix
[ ] Feature
```
When running the `npm run prettier-check` command on MacOs not all files are checked by Prettier.
When running the `npm run prettier-check` command on MacOs  all files are checked by Prettier. The same command works correctly on Windows.
```
[ ] Yes
[x] No
```

fix(build): add quotes around the Prettier parameters to fix an issue on MacOS

---

packages/stark-build/package.json
showcase/package.json
showcase/src/polyfills.browser.ts
starter/package.json
starter/src/polyfills.browser.ts

```
[ ] Bugfix
[ ] Feature
```
Currently Stark has the following packages that are either obsolete or no longer necessary:
- **"@types/source-map"** is obsolete due to:
```npm WARN deprecated @types/source-map@0.5.7: This is a stub types definition for source-map (https://github.com/mozilla/source-map). source-map provides its own type definitions, so you don't need @types/source-map installed!```
- **"web-animations-js"** is no longer necessary as of Angular 6. See …

chore(stark-all): remove obsolete and unnecessary NPM dependencies

---

showcase/src/app/router.config.ts
starter/src/app/router.config.ts

```
[ ] Bugfix
[ ] Feature
```
UI-Router visualizer is always enabled in the Starter and in the Showcase.
- In the Starter, the UI-Router visualizer is enabled only in DEV.
- In the Showcase, the visualizer is always disabled since it is not needed for the moment. It can be enabled again if needed for development purposes.
```
[ ] Yes
[X] No
```

refactor(stark-starter): enable UI-Router visualizer only in development. Disable visualizer in showcase

---

packages/rollup.config.common-data.js
packages/stark-core/package.json
showcase/src/app/app.module.ts
starter/src/app/app.module.ts

ISSUES CLOSED: #81, #117
```
[ ] Bugfix
[X] Feature
```
Issue Number: #81 #117 
NgRx Store DevTools integrated in the Starter and the Showcase as suggested in https://github.com/ngrx/platform/blob/master/docs/store-devtools/README.md.
In Chrome:
In Firefox:
```
[ ] Yes
[X] No
```

feat(stark-core): add @ngrx-store-devtools package. Integrate store dev tools in showcase and starter

---

packages/stark-core/package.json
packages/stark-ui/package.json

```
[X] Bugfix
[ ] Feature
```
As a result of the PR #516, the new `lint-css` command in stark-core and stark-ui also lints the CSS files in the "coverage" and "reports" folders which are created by the unit tests. This causes the `lint-css` command to fail due to many violations which should not be in the scope of the linting.
The `lint-css` command in stark-core and stark-ui only includes the files from the "src" and "assets" folders.
```
[ ] Yes
[X] No
```

fix(stark-ui): include only "src" and "assets" folders in "lint-css" command

---

showcase/ghpages-adapt-bundle-urls.js

ISSUES CLOSED: #571
```
[X] Bugfix
[ ] Feature
```
Issue Number: #571 
The baseUrl and deployUrl are correctly replaced in all files in "latest" and the "next version" of the Showcase.
```
[ ] Yes
[X] No
```

fix(stark-demo): add missing files and regex to the showcase url auto-replace script

---

.release-it.json

ISSUES CLOSED: #574
```
[X] Bugfix
[ ] Feature
```
Issue Number: #574 
The version of the Stark packages is automatically updated by release-it in both the `package.json` and `package-lock.json` files.
```
[ ] Yes
[X] No
```

fix(release): add "package-lock.json" to the set of files to be updated by release-it

---

.travis.yml
package-lock.json
package.json
packages/stark-build/config/webpack.common.js
packages/stark-build/config/webpack.prod.js
showcase/package.json

ISSUES CLOSED: #572
```
[X] Bugfix
[ ] Feature
```
Issue Number: #572
Travis build for each PR is faster
```
[ ] Yes
[X] No
```

fix(build): add an argument for build prod when it is a Test CI. Adapt travis.yml to use it

---

CHANGELOG.md

```
[ ] Bugfix
[ ] Feature
```
The Changelog generated during the latest release is wrong: all the changes from the `10.0.0-alpha.4` version are merged with the ones from the `10.0.0-alpha.3` version.
The cause of the issue is that the tag `10.0.0-alpha.3` is set in the wrong commit instead of being set in the "release" commit.
- The tag has been fixed and it is now set in the "release" commit of version `10.0.0-alpha.3`
- The auto-generated log contains now the …

chore(docs): re-generate changelog after fixing tag 10.0.0-alpha.3

---

packages/stark-core/src/modules/http/testing/http.mock.ts
showcase/src/app/demo/action-bar/action-bar.component.html
showcase/src/app/demo/button/button.component.html
showcase/src/app/demo/example-viewer/example-viewer.component.html
showcase/src/app/demo/keyboard-directives/keyboard-directives.component.html
showcase/src/app/demo/pretty-print/pretty-print.component.html
showcase/src/app/shared/example-viewer/example-viewer.component.html
showcase/src/app/shared/example-viewer/example-viewer.component.spec.ts
showcase/src/app/shared/example-viewer/example-viewer.component.ts
showcase/src/app/shared/example-viewer/file.service.ts

ISSUES CLOSED: #575 #580
```
[ ] Bugfix
[X] Feature
```
Issue Number: #575 #580 
- The ExampleViewer fetches the example files from the correct url taking into account the base URL of the app when deployed in GitHub Pages.
- The ExampleViewer does not show a tooltip anymore when hovering over the component.
```
[ ] Yes
[X] No
```

fix(stark-demo): adapt ExampleViewer to fetch example files targeting the right url. Rename title input to prevent weird tooltip.

---

package-lock.json
packages/stark-build/package-lock.json
packages/stark-core/package-lock.json
packages/stark-testing/package-lock.json
packages/stark-ui/package-lock.json
showcase/package-lock.json
starter/package-lock.json

```
[X] Bugfix
[ ] Feature
```
Travis builds are failing due to an NPM error:
```
npm ERR! enoent ENOENT: no such file or directory, rename '/home/travis/build/NationalBankBelgium/stark/packages/stark-core/node_modules/.staging/@nationalbankbelgium/stark-testing-c8dfe007/node_modules/@types/jasmine' -> '/home/travis/build/NationalBankBelgium/stark/packages/stark-core/node_modules/.staging/@types/jasmine-efe0cc22'
```
The `package-lock.json` files of all stark packages …

ci(stark-all): fix package-lock.json files that were corrupted in #610 for all stark packages

---

.travis.yml

```
[ ] Bugfix
[ ] Feature
```
Travis builds fail due to the `npm pack` command triggered in our `build.sh` suddenly stops and executes the next command `adaptNpmPackageDependencies` which fails.
The `npm pack` is executed correctly and the command `adaptNpmPackageDependencies` is executed afterwards as soon as the `npm pack` finishes.
```
[ ] Yes
[X] No
```

ci(stark-build): downgrade npm back to 5.8.0 due to 'npm pack' failure on Travis

---

.travis.yml

```
[ ] Bugfix
[ ] Feature
```
PRs submitted by GreenKeeper fail due to an NPM error:
```
npm ERR! enoent ENOENT: no such file or directory, rename '/home/travis/build/NationalBankBelgium/stark/packages/stark-core/node_modules/.staging/@nationalbankbelgium/stark-testing-c8dfe007/node_modules/@types/jasmine' -> '/home/travis/build/NationalBankBelgium/stark/packages/stark-core/node_modules/.staging/@types/jasmine-efe0cc22'
```
The issue seems to be related to the fact …

ci(build-main): adapt travis config to remove all package-lock.json before installing all packages on PRs from GreenKeeper

---

.travis.yml

```
[X] Bugfix
[ ] Feature
```
Greenkeeper-lockfile does not work and we use an old version of it.
Greenkeeper-lockfile version is updated and I hope that will fix our issue 😊 
```
[ ] Yes
[X] No
```
See https://github.com/greenkeeperio/greenkeeper-lockfile/issues/164 for having more info about the new version

fix(build-main): fix version of greenkeeper-lockfile which is installed during travis build

---

.travis.yml
build.sh
packages/rollup.config.common-data.js
packages/stark-ui/src/modules/action-bar/action-bar.module.ts
packages/stark-ui/src/modules/app-logo/components/app-logo.component.scss
packages/stark-ui/src/modules/date-picker/date-picker.module.ts
packages/stark-ui/src/modules/date-range-picker/date-range-picker.module.ts
packages/stark-ui/src/modules/dropdown/components/dropdown.component.ts
showcase/src/styles/_stark-styles.scss
showcase/src/styles/_theme.scss
showcase/src/styles/styles.pcss
showcase/src/styles/styles.scss

Change BrowserModule for CommonModule in 3 stark-ui modules.
Fix rollup unresolved dependecy linked to dropdown component.
Adapt styles in App-Logo component from pcss to scss.
Allow build showcase to take up to 20 minutes before triggering timeout
in Travis.
```
[X] Bugfix
[ ] Feature
```
Build copies some unused files during "assets copy". 
Styles are not organized correctly in the showcase.
BrowserModule is incorrectly used in some stark-ui modules.
Travis failed …

fix(stark-all): change BrowserModule for CommonModule. Rearrange styles in showcase. Improve build script

---

packages/stark-ui/assets/styles/_header.scss
packages/stark-ui/src/modules/app-logo/components/app-logo.component.scss
showcase/src/app/app.component.html

ISSUES CLOSED: #583
```
[x] Bugfix
[ ] Feature
```
The app-logo is not yet implemented in the showcase
The app-logo is displayed too big.
#583 
The app-logo is added to the Showcase
The app-logo size is displayed with the correct size.
```
[ ] Yes
[x] No
```

fix(stark-ui): modify css and add App-Logo to Showcase

---

.release-it.json

ISSUES CLOSED: #669
```
[X] Bugfix
[ ] Feature
```
Issue Number: #669 
The `pushRepo` option of the release-it config is now set to `"origin"` as the default config according to the changes made in this commit https://github.com/webpro/release-it/commit/948fb1b8e8fc75e0a448d1e25106ef73b856c98e aimed to solve this issue https://github.com/webpro/release-it/issues/306
```
[ ] Yes
[X] No
```

fix(release): fix wrong pushRepo option in release-it according to the latest version

---

packages/stark-ui/src/modules/pretty-print/components/pretty-print.component.ts

ISSUES CLOSED: #513
```
[ ] Bugfix
[ ] Feature
```
The use of the PrismJS css file is not documented.
Issue Number: #513 
The use of the PrismJS css file is added to the pretty-print documentation.
```
[ ] Yes
[x] No
```

docs(stark-ui): document the need for importing the PrismJS css file.

---

packages/stark-ui/assets/styles/_colors.scss
packages/stark-ui/assets/styles/_variables.scss
packages/stark-ui/assets/themes/_button-theme.scss
packages/stark-ui/assets/themes/_card-theme.scss
packages/stark-ui/src/common/classes/abstract-component.ts
packages/stark-ui/src/modules/action-bar/components/_action-bar-theme.scss
packages/stark-ui/src/modules/dropdown/components/_dropdown-theme.scss
packages/stark-ui/src/modules/dropdown/components/dropdown.component.ts

ISSUES CLOSED: #662
```
[ ] Bugfix
[x] Feature
```
Issue Number: #662
The end user has now a global simplified SCSS map to set the colors but he can still uses the full palette.
Add an input to the dropdown so its color can be set by a parent component (LanguageSelector for instance)
```
[ ] Yes
[x] No
```

feat(stark-ui): color settings

---

package-lock.json
package.json
packages/stark-build/package-lock.json
packages/stark-core/package-lock.json
packages/stark-core/package.json
packages/stark-testing/package-lock.json
packages/stark-ui/package-lock.json
packages/stark-ui/package.json
packages/stark-ui/src/modules/keyboard-directives/directives/on-enter-key.directive.spec.ts
packages/stark-ui/src/modules/keyboard-directives/directives/on-enter-key.directive.ts
packages/stark-ui/src/modules/keyboard-directives/directives/restrict-input.directive.spec.ts
packages/stark-ui/src/modules/keyboard-directives/directives/restrict-input.directive.ts
showcase/package-lock.json
showcase/package.json
starter/package-lock.json
starter/package.json

ISSUES CLOSED: #684
```
[ ] Bugfix
[X] Feature
```
Issue Number: #684 
- Stark uses Typescript 2.8.4.
- The keyboard directives no longer use deprecated DOM API (except the deprecated [KeyboardEvent.charCode](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/charCode) to keep compatibility with Internet Explorer).
```
[ ] Yes
[X] No
```
Took the chance to re-install all the dependencies to update the package-lock.json files.

chore(stark-all): upgrade Typescript to v2.8. Fix keyboard directives due to new deprecations in Typescript 2.8 DOM API.

---

packages/stark-ui/src/modules/breadcrumb/components/breadcrumb.component.spec.ts
packages/stark-ui/src/modules/breadcrumb/components/breadcrumb.component.ts
packages/stark-ui/src/modules/language-selector/components/language-selector.component.spec.ts
packages/stark-ui/src/modules/session-ui/pages/login/login-page.component.spec.ts
packages/stark-ui/src/modules/session-ui/pages/preloading/preloading-page.component.spec.ts
packages/stark-ui/src/modules/session-ui/pages/preloading/preloading-page.component.ts
packages/stark-ui/src/modules/session-ui/pages/session-expired/session-expired-page.component.spec.ts
packages/stark-ui/src/modules/session-ui/pages/session-logout/session-logout-page.component.spec.ts
packages/stark-ui/src/modules/slider/components/slider.component.spec.ts
packages/stark-ui/src/modules/toast-notification/services/toast-notification.service.spec.ts

ISSUES CLOSED: #726
```
[X] Bugfix
[ ] Feature
```
Issue Number: #726 
The Preloading page now does a session login with the fetched user in order to correctly initialize the app and navigate to the home page.
```
[ ] Yes
[X] No
```
Minor fixes in some other unit tests.

fix(stark-ui): perform the session login in the Preloading page after fetching the user profile

---

package.json

```
[ ] Bugfix
[X] Feature
```
With the upgrade of [Husky](https://github.com/typicode/husky) from v0.14.3 to v1.1.0, the git hooks are not executing anymore since [the way they should be defined has changed in the latest version](https://github.com/typicode/husky#upgrading-from-014).
The git hooks in husky are adapted so they are executed correctly.
```
[ ] Yes
[X] No
```

chore(stark-all): adapt husky hooks after Husky upgrade

---

packages/stark-ui/src/modules/app-menu/components/app-menu-config.intf.ts
packages/stark-ui/src/modules/app-menu/components/app-menu-entry.intf.ts
packages/stark-ui/src/modules/app-menu/components/app-menu-group.intf.ts
packages/stark-ui/src/modules/app-menu/components/app-menu-item.component.html
packages/stark-ui/src/modules/app-menu/components/app-menu-item.component.ts
packages/stark-ui/src/modules/app-menu/components/app-menu-section.intf.ts
packages/stark-ui/src/modules/app-menu/components/app-menu.component.html
packages/stark-ui/src/modules/app-menu/components/app-menu.component.spec.ts
packages/stark-ui/src/modules/app-menu/components/app-menu.component.ts
packages/stark-ui/src/modules/app-sidebar/components/app-sidebar.component.spec.ts
packages/stark-ui/src/modules/breadcrumb/components/breadcrumb.component.spec.ts
packages/stark-ui/src/modules/date-range-picker/components/date-range-picker.component.spec.ts
packages/stark-ui/src/modules/date-range-picker/components/date-range-picker.component.ts
showcase/src/app/app.component.html
showcase/src/app/demo/menu/demo-menu.component.html
showcase/src/assets/examples/menu/sections.html
showcase/src/assets/examples/menu/simple.html
starter/src/app/app.component.html

ISSUES CLOSED: #755
```
[ ] Bugfix
[X] Feature
```
Issue Number: #755
The AppMenu supports translation keys in the menu entry label which are correctly translated into the different languages of the app.
```
[ ] Yes
[X] No
```

feat(stark-ui): integrate translation support in AppMenu component

---

package-lock.json
packages/stark-core/src/modules/session/entities/session-config.entity.intf.ts
packages/stark-core/src/modules/session/services/session.service.spec.ts
packages/stark-core/src/modules/session/services/session.service.ts
packages/stark-core/src/modules/session/session.module.ts
packages/stark-ui/src/modules/app-footer/components/app-footer.component.spec.ts
packages/stark-ui/src/modules/app-logout/components/app-logout.component.spec.ts
packages/stark-ui/src/modules/app-logout/components/app-logout.component.ts
packages/stark-ui/src/modules/app-menu/components/app-menu-item.component.ts
packages/stark-ui/src/modules/session-ui/components/app-container.component.html
packages/stark-ui/src/modules/session-ui/components/app-container.component.ts
packages/stark-ui/src/modules/session-ui/pages/login.ts
packages/stark-ui/src/modules/session-ui/pages/login/_login-page.component.scss
packages/stark-ui/src/modules/session-ui/pages/preloading/_preloading-page.component.scss
packages/stark-ui/src/modules/session-ui/pages/session-expired/_session-expired-page.component.scss
packages/stark-ui/src/modules/session-ui/pages/session-logout/_session-logout-page.component.scss
packages/stark-ui/src/modules/session-ui/session-ui.module.ts

ISSUES CLOSED: #727
```
[ ] Bugfix
[X] Feature
```
Issue Number: #727 
All "Init" and "Exit" states managed by the Stark Session module are configurable via the `StarkSessionConfig` object passed in the `forRoot()` method.
```
[ ] Yes
[X] No
```
Took the change to re-generate the root `package-lock.json` file.

feat(stark-core): allow customizing Login and Preloading states via the StarkSessionConfig

---

packages/stark-core/src/modules/routing/services/routing.service.spec.ts
packages/stark-core/src/modules/routing/services/routing.service.ts

Adapt Routing Service isCurrentUiState() to take into account inherited params.
ISSUES CLOSED: #769
```
[X] Bugfix
[ ] Feature
```
Issue Number: #769
The state history saved by the Routing Service now contains also the inherited params. This is also reflected in the results of these methods
- `navigateToPrevious()`
- `getStateTreeParams()`
- `isCurrentUiState()`
```
[ ] Yes
[X] No
```

fix(stark-core): include inherited params from ancestor routing states in navigation history

---

packages/stark-core/src/modules/session/services/session.service.spec.ts
packages/stark-core/src/modules/session/services/session.service.ts
packages/stark-core/src/modules/session/session.module.ts

ISSUES CLOSED: #797
```
[X] Bugfix
[ ] Feature
```
Issue Number: #797 #727 
AOT Production build succeeds even if a session config object is passed to the `SessionModule.forRoot()`.
```
[ ] Yes
[X] No
```

refactor(stark-core): refactor logic to validate StarkSessionConfig to prevent Angular AOT error "Function calls are not supported in decorators"

---

packages/stark-build/config/webpack.common.js
packages/stark-build/config/webpack.prod.js

ISSUES CLOSED: #623
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #623 #585 
- The PurifyPlugin is no longer used since it is already [deprecated in Angular 6.1](https://github.com/angular/devkit/commit/cb2703e4a44a3055f5bc6284883d39d6c6dc1f00) and [removed in Angular 7](https://github.com/angular/angular-cli/pull/12171/files).
- The number of minification "passes" is set to 1 when running on the CI environment (Travis).
- The `prettier` parsers as well as the …

perf(stark-build): remove deprecated Angular PurifyPlugin. Enhance UglifyJs options to improve performance

---

showcase/src/app/_app.component-theme.scss
showcase/src/app/_app.component.scss
showcase/src/app/app.component.html
showcase/src/assets/translations/en.json
showcase/src/assets/translations/fr.json
showcase/src/assets/translations/nl.json
showcase/src/styles/_theme.scss
showcase/src/styles/styles.scss

ISSUES CLOSED: #741 
```
[ ] Bugfix
[X] Feature
```
Icons in the header were not leading to anything
Issue Number: #741 
Buttons now lead to the github page of the project and stark-ui/stark-core documentation
```
[ ] Yes
[x] No
```

feat(showcase): reimplementation of the buttons in the header

---

packages/stark-core/src/modules/settings/settings.module.ts
packages/stark-ui/assets/styles/_old-variables.scss
packages/stark-ui/src/modules.ts
packages/stark-ui/src/modules/app-menu/components/_app-menu.component.scss
packages/stark-ui/src/modules/minimap.ts
packages/stark-ui/src/modules/minimap/components.ts
packages/stark-ui/src/modules/minimap/components/_minimap-theme.scss
packages/stark-ui/src/modules/minimap/components/_minimap.component.scss
packages/stark-ui/src/modules/minimap/components/item-properties.intf.ts
packages/stark-ui/src/modules/minimap/components/item-visibility.intf.ts
packages/stark-ui/src/modules/minimap/components/minimap.component.html
packages/stark-ui/src/modules/minimap/components/minimap.component.spec.ts
packages/stark-ui/src/modules/minimap/components/minimap.component.ts
packages/stark-ui/src/modules/minimap/minimap.module.ts
showcase/src/app/app.component.ts
showcase/src/app/app.module.ts
showcase/src/app/demo/demo.module.ts
showcase/src/app/demo/index.ts
showcase/src/app/demo/minimap/demo-minimap.component.html
showcase/src/app/demo/minimap/demo-minimap.component.ts
showcase/src/app/demo/minimap/index.ts
showcase/src/app/demo/routes.ts
showcase/src/assets/examples/minimap/compact.html
showcase/src/assets/examples/minimap/compact.ts
showcase/src/assets/examples/minimap/full.html
showcase/src/assets/examples/minimap/full.ts
showcase/src/assets/translations/en.json
showcase/src/assets/translations/fr.json
showcase/src/assets/translations/nl.json
showcase/src/styles/_stark-styles.scss

ISSUES CLOSED: #758 
```
[ ] Bugfix
[x] Feature
```
Issue Number: #758 
The minimap composent is now implemented
```
[ ] Yes
[x] No
```

 feat(stark-ui): implementation of minimap component

---

packages/stark-build/config/webpack.dev.js
showcase/src/app/demo/typography/demo-typography.component.html
showcase/src/app/demo/typography/demo-typography.component.ts
showcase/src/assets/translations/en.json
showcase/src/assets/translations/fr.json
showcase/src/assets/translations/nl.json
showcase/src/styles/_variables.scss
starter/src/styles/_variables.scss

ISSUES CLOSED #768 
```
[x] Bugfix
[ ] Feature
```
There is confusion about adding custom fonts and no way to add a font from a CDN.
Issue Number: #768
```
[ ] Yes
[x] No
```

feat(stark-build): add "cspFontSrc" as configurable property to webpack dev server. Add docs to Showcase about adding custom fonts.

---

showcase/src/polyfills.browser.ts
starter/src/polyfills.browser.ts

ISSUES CLOSED: #828 
```
[x] Bugfix
[ ] Feature
```
Implementations of the `pretty-print` component which use the format "css", "scss", "json", "javascript" or "typescript" are not formatted / highlighted in IE11.
Issue Number: #828
With the addition of a polyfill for `String.prototype.trimRight` the issue is resolved.
This is because the dependency `prettier` uses this function.
```
[ ] Yes
[x] No
```

fix(stark-demo): add String trimRight polyfill to fix issue with PrettyPrint component in IE11

---

packages/stark-core/src/modules/session/session.module.ts
showcase/src/app/app.module.ts
starter/src/app/app.module.ts

ISSUES CLOSED: #90, #98
```
[ ] Bugfix
[ ] Feature
```
The `NgIdleModule` and `NgIdleKeepaliveModule` are imported in the `AppModule` in the Starter and the Showcase but the npm dependencies of such libraries are defined in Stark-Core.
Issue Number: #90 #98 
The `NgIdleModule` and `NgIdleKeepaliveModule` are now imported in the `StarkSessionModule` from Stark-Core where they should be since they are used internally and the npm dependencies of such libraries are also …

refactor(stark-core): move NgIdleModule and NgIdleKeepaliveModule imports to StarkSessionModule

---

.travis.yml

```
[ ] Bugfix
[ ] Feature
```
The waiting time in Travis for the generation of the production build of the Showcase is by default 20 mins (see [travis_wait)](https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received) which is not enough in Node 6 as it often takes longer than that which causes the build to fail.
The wait time in Travis has been extended to 25 mins which should be enough for Node 6.
```
[ ] Yes
[X] No
```

ci(stark-demo): increase Travis wait time for the generation of the Showcase production build

---

.travis.yml

```
[ ] Bugfix
[ ] Feature
```
The waiting time in Travis for the generation of the production build of the Showcase is by default 20 mins (see [travis_wait)](https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received) which is not enough in Node 6 as it often takes longer than that which causes the build to fail.
The wait time in Travis has been extended to 30 mins which should be enough for Node 6.
```
[ ] Yes
[X] No
```

ci(stark-demo): increase Travis wait time to 30 mins for the generation of the Showcase prod build

---

build-functions.sh

```
[X] Bugfix
[ ] Feature
```
After upgrading NPM to the latest version (6.4.1), Travis builds fail due to the `npm pack` command triggered in our `build.sh` suddenly stops and executes the next command `adaptNpmPackageDependencies` which fails.
Same issue described in this PR: #615 
The `--silent` options is used in the  `npm pack` so that it is executed correctly and without logging anything to the console so that the command `adaptNpmPackageDependencies` is …

ci(build-main): add 'silent' flag to npm pack command to prevent Travis from continuing to the next step before the packaging finishes

---

packages/stark-core/src/modules/http/builder/http-abstract-base-request-builder.intf.ts
packages/stark-core/src/modules/http/builder/http-abstract-base-request-builder.ts
packages/stark-core/src/modules/http/builder/http-request-builder.spec.ts
packages/stark-core/src/modules/http/entities/http-request.entity.intf.ts
packages/stark-core/src/modules/http/services/http.service.spec.ts
packages/stark-core/src/modules/http/services/http.service.ts
packages/stark-core/src/modules/session/services/session.service.intf.ts
packages/stark-core/src/modules/session/services/session.service.spec.ts
packages/stark-core/src/modules/session/services/session.service.ts

ISSUES CLOSED: #856
```
[X] Bugfix
[ ] Feature
```
Issue Number: #856
The correlationId Http header is not added in case the correlation id is not defined (which is the case when the `loggingFlushDisabled` is true).
```
[ ] Yes
[X] No
```

fix(stark-core): refactor Http headers related API to prevent undefined and null header values to be added to Angular Http headers

---

docs/TIMEOUT_WARNING.md
packages/stark-build/config/webpack.dev.js
packages/stark-ui/assets/styles/_media-queries.scss
packages/stark-ui/src/modules/minimap/components/_minimap-theme.scss
packages/stark-ui/src/modules/session-ui.ts
packages/stark-ui/src/modules/session-ui/assets/translations/en.ts
packages/stark-ui/src/modules/session-ui/assets/translations/fr.ts
packages/stark-ui/src/modules/session-ui/assets/translations/nl.ts
packages/stark-ui/src/modules/session-ui/components.ts
packages/stark-ui/src/modules/session-ui/components/_session-timeout-warning-dialog.component.scss
packages/stark-ui/src/modules/session-ui/components/session-timeout-warning-dialog.component.html
packages/stark-ui/src/modules/session-ui/components/session-timeout-warning-dialog.component.spec.ts
packages/stark-ui/src/modules/session-ui/components/session-timeout-warning-dialog.component.ts
packages/stark-ui/src/modules/session-ui/effects.ts
packages/stark-ui/src/modules/session-ui/effects/session-timeout-warning.effect.spec.ts
packages/stark-ui/src/modules/session-ui/effects/session-timeout-warning.effects.ts
packages/stark-ui/src/modules/session-ui/entities.ts
packages/stark-ui/src/modules/session-ui/entities/stark-session-ui-config.ts
packages/stark-ui/src/modules/session-ui/pages/preloading/preloading-page.component.ts
packages/stark-ui/src/modules/session-ui/pages/session-expired/session-expired-page.component.ts
packages/stark-ui/src/modules/session-ui/pages/session-logout/session-logout-page.component.ts
packages/stark-ui/src/modules/session-ui/session-ui.module.ts
showcase/src/app/getting-started/getting-started-component/_getting-started-theme.scss
showcase/src/app/shared/table-of-contents/table-of-contents.component.scss
starter/src/styles/_stark-styles.scss

ISSUES CLOSED: #719 
```
[ ] Bugfix
[x] Feature
```
Issue Number: #119 #719 
A new SessionTimeoutWarning dialog will be displayed when the user is inactive for too long, along with a timer. 
```
[ ] Yes
[x] No
```

feat(stark-ui): implementation of a session timeout warning

---

.release-it.json

ISSUES CLOSED: #976
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #976 
The release-it config is migrated as indicated in the [v9 changelog](https://github.com/webpro/release-it/blob/master/CHANGELOG.md#v9) so no more deprecation warnings are displayed when running the `npm run release` command.
```
[ ] Yes
[X] No
```

chore(release): adapt release-it config to align with the new config since version 9

---

packages/stark-ui/src/modules/table/components/column.component.ts
packages/stark-ui/src/modules/table/components/table.component.html
packages/stark-ui/src/modules/table/components/table.component.ts
showcase/src/app/demo-ui/components/table-regular/table-regular.component.ts
showcase/src/app/demo-ui/components/table-with-custom-actions/table-with-custom-actions.component.ts
showcase/src/app/demo-ui/components/table-with-custom-styling/table-with-custom-styling.component.ts
showcase/src/app/demo-ui/components/table-with-fixed-header/table-with-fixed-header.component.ts
showcase/src/app/demo-ui/components/table-with-selection/table-with-selection.ts
showcase/src/assets/translations/en.json
showcase/src/assets/translations/fr.json
showcase/src/assets/translations/nl.json

CLOSED: #954, #955
```
[X] Bugfix
[ ] Feature
```
Issue Number: #954 #955 
* The column header label is now translated in the table component
* A default filter is now assigned if no filter configuration is passed to the table component.  
```
[ ] Yes
[X] No
```

fix(stark-ui): fixes for Table component: not initialized filter + not translated column headers

---

packages/stark-ui/src/common/translations/translations/en.ts
packages/stark-ui/src/common/translations/translations/fr.ts
packages/stark-ui/src/common/translations/translations/nl.ts
packages/stark-ui/src/modules/dropdown/components/dropdown.component.html
packages/stark-ui/src/modules/dropdown/components/dropdown.component.spec.ts
packages/stark-ui/src/modules/dropdown/components/dropdown.component.ts
packages/stark-ui/src/modules/dropdown/dropdown.module.ts
packages/stark-ui/src/modules/language-selector/components/language-selector.component.html
packages/stark-ui/src/modules/pagination/components/pagination.component.html
packages/stark-ui/src/modules/pagination/components/pagination.component.spec.ts
packages/stark-ui/src/modules/pagination/components/pagination.component.ts
packages/stark-ui/src/util.ts
packages/stark-ui/src/util/form.ts
packages/stark-ui/src/util/form/form.util.spec.ts
packages/stark-ui/src/util/form/form.util.ts
showcase/src/app/demo-ui/pages/dropdown/demo-dropdown-page.component.html
showcase/src/app/demo-ui/pages/dropdown/demo-dropdown-page.component.ts
showcase/src/assets/examples/dropdown/multiple-required-selection.html
showcase/src/assets/examples/dropdown/multiple-selection.html
showcase/src/assets/examples/dropdown/reactive-form-dropdown.html
showcase/src/assets/examples/dropdown/reactive-form-dropdown.ts
showcase/src/assets/examples/dropdown/single-blank-selection.html
showcase/src/assets/examples/dropdown/single-required-selection.html
showcase/src/assets/examples/dropdown/white.html
showcase/src/assets/translations/en.json
showcase/src/assets/translations/fr.json
showcase/src/assets/translations/nl.json

ISSUES CLOSED: #982 
```
[X] Bugfix
[X] Feature
```
The dropdown component has no support for Reactive form.
Issue Number: #982 
Dropdown component is based only on Reactive Form but still accepts `value` + `selectionChanged` tobe able to use it. The developer can define himself the formControl object by passing via the input `dropdownFormControl`.
Form utils have been added to Stark.
```
[X] Yes
[ ] No
```

feat(stark-ui): make dropdown component working with reactive form + add stark form util

---

packages/stark-ui/src/modules/app-sidebar/components/app-sidebar.component.html
packages/stark-ui/src/modules/app-sidebar/components/app-sidebar.component.spec.ts
packages/stark-ui/src/modules/app-sidebar/components/app-sidebar.component.ts

feat(stark-ui): add option to close sidebar after navigation
- Added property `closeOnNavigate` to `stark-app-sidebar`, when this is set to true the sidebar will automatically close after navigating on smaller devices.
- Added tests for new feature
ISSUES CLOSED: #995
fix(stark-ui): keep scroll position after closing sidenav
  - set `autofocus` of `mat-sidenav` to `false`
ISSUES CLOSED: #750
```
[ ] Bugfix
[x] Feature
```
Issue Number: #995 & #750 
If `closeOnNavigate` …

fix(stark-ui): close sidebar after navigation. Keep sidebar scroll position

---

packages/stark-ui/assets/styles/_material-fixes.scss
packages/stark-ui/assets/themes/_button-theme.scss
showcase/src/app/app.module.ts
showcase/src/app/shared/shared.module.ts

- add StarkSvgViewBoxModule to shared modules
Closes #504 
- offset icon slightly to compensate @angular/material update
- update icon scaling functionality after correct `starkSvgViewBox` implementation
Closes #1030 
```
[x] Bugfix
[ ] Feature
```
Issue Number: #504 #1030 
```
[ ] Yes
[x] No
```

fix(stark-ui): fix icons not displaying correctly

---

build-functions.sh

ISSUES CLOSED: #1051 
```
[X] Bugfix
[ ] Feature
```
The Travis build for the master branch is currently broken due to the following error during the installation of dependencies in the Starter:
Issue Number: #1051 
```
npm ERR! cipm can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
```
Which means that the `package-lock.json` has different …

fix(build-main): adapt regex pattern to include 'resolved' in package-lock.json replacement

---

packages/stark-build/config/build-utils.js
packages/stark-build/config/ng-cli-utils.js
packages/stark-build/config/webpack.common.js
packages/stark-build/config/webpack.dev.js
packages/stark-build/config/webpack.prod.js
showcase/angular.json
showcase/src/app/app.module.ts
starter/angular.json
starter/src/app/app.module.ts

ISSUES CLOSED: #1070
```
[ ] Bugfix
[X] Feature
```
Issue Number: #1070
Stark-build now process correctly the global styles set in the `package.json` under `projects -> your-app -> architect -> build -> options -> styles` in the same way Angular CLI does.
```
[X] Yes
[ ] No
```

feat(stark-build): adapt build utils and webpack config to read global styles from angular.json to align with Angular CLI

---

packages/stark-core/src/modules/session/services/session.service.spec.ts

ISSUES CLOSED: #1091
```
[x] Bugfix
[ ] Feature
```
In the `session.service.spec.ts` file the following code produces a TS compilation error on the latest version of Rxjs (6.4.0) due to a [change in the typings of `defer`](https://github.com/reactivex/rxjs/commit/5aea50e):
```typescript
defer<boolean>(() => onBeforeHookCallback()).subscribe(
(result: boolean) => {
expect(result).toBe(true);
},
() => {
fail("The 'error' function should not be called in case of …
```

fix(stark-core): adapt code to fix typings issue with Rxjs 6.4.0

---

package-lock.json
package.json
showcase/package-lock.json
showcase/package.json
starter/package-lock.json
starter/package.json

```
[ ] Bugfix
[ ] Feature
```
The root `package.json` has a different Rxjs version from those in the Starter and the Showcase due to the fact that they accept different ranges: minor versions in the root and only patch versions in the Showcase and Starter.
Now the root, Showcase and Starter have the same version of Rxjs and they also accept the same ranges: minor version (`^`)
```
[ ] Yes
[X] No
```

chore(build): loosen rxjs version to accept minor version upgrades in root, Starter and Showcase

---

greenkeeper.json

```
[ ] Bugfix
[ ] Feature
```
Greenkeeper creates PRs to upgrade some libraries that we cannot upgrade right away:
- `@types/node`: we use Node 8 for the moment instead of the latest versions
- `@angular/flex-layout`: latest versions depend on Typescript 3.2, but we are still on 3.1 (due to IntelliJ mainly)
`@types/node` and `@angular/flex-layout` are now ignored by Greenkeeper.
```
[ ] Yes
[X] No
```

chore(stark-all): add @types/node and @angular/flex-layout to ignored libs in greenkeeper.json

---

showcase/src/app/app-menu.config.ts
showcase/src/app/styleguide/pages/index.ts
showcase/src/app/styleguide/pages/layout/index.ts
showcase/src/app/styleguide/pages/layout/styleguide-layout-page.component.html
showcase/src/app/styleguide/pages/layout/styleguide-layout-page.component.scss
showcase/src/app/styleguide/pages/layout/styleguide-layout-page.component.ts
showcase/src/app/styleguide/pages/layout/styleguide-layout-page.theme.scss
showcase/src/app/styleguide/routes.ts
showcase/src/app/styleguide/styleguide.module.ts
showcase/src/assets/examples/flex-layout/flex.html
showcase/src/assets/examples/flex-layout/flex.scss
showcase/src/assets/examples/flex-layout/grid.html
showcase/src/assets/examples/flex-layout/grid.scss
showcase/src/assets/translations/en.json
showcase/src/assets/translations/fr.json
showcase/src/assets/translations/nl.json
showcase/src/styles/_theme.scss
showcase/src/styles/styles.scss

ISSUES CLOSED: #668
```
[ ] Bugfix
[x] Feature
```
Issue Number: #668, #106
A new page under style guide called layout with a demo of Stark-layout
```
[ ] Yes
[x] No
```
Internal Confluence is also updated

feat(stark-demo): add 'styleguide/layout' page for documenting the use of Angular Flex-layout

---

packages/stark-core/src/modules/http/entities/http-parameter-codec.ts
packages/stark-core/src/modules/http/services/http.service.spec.ts
packages/stark-core/src/modules/http/services/http.service.ts
packages/stark-core/src/util.ts
packages/stark-core/src/util/http.util.spec.ts
packages/stark-core/src/util/http.util.ts
packages/stark-core/src/util/util-helpers.ts

- extracted `convertMapIntoObject` function to separate file
- added `convertStarkQueryParamsIntoHttpParams` function to correctly handle params in the http module
- extended `HttpParameterCodec` according to [this solution](https://github.com/angular/angular/issues/18261#issuecomment-426383787)
- updated `http.util.spec.ts` according to new implementation
- test `convertStarkQueryParamsIntoHttpParams`
ISSUES CLOSED: #1130
```
[x] Bugfix
[ ] Feature
```
Issue Number: …

fix(stark-core): use custom encoder for URL query parameters

---

packages/stark-ui/src/modules.ts
packages/stark-ui/src/modules/transform-input-directive.ts
packages/stark-ui/src/modules/transform-input-directive/directives.ts
packages/stark-ui/src/modules/transform-input-directive/directives/transform-input.directive.spec.ts
packages/stark-ui/src/modules/transform-input-directive/directives/transform-input.directive.ts
packages/stark-ui/src/modules/transform-input-directive/transform-input-directive.module.ts
showcase/src/app/app-menu.config.ts
showcase/src/app/demo-ui/demo-ui.module.ts
showcase/src/app/demo-ui/pages/index.ts
showcase/src/app/demo-ui/pages/keyboard-directives/demo-keyboard-directives-page.component.html
showcase/src/app/demo-ui/pages/keyboard-directives/demo-keyboard-directives-page.component.scss
showcase/src/app/demo-ui/pages/transform-input-directive/demo-transform-input-directive-page.component.html
showcase/src/app/demo-ui/pages/transform-input-directive/demo-transform-input-directive-page.component.ts
showcase/src/app/demo-ui/pages/transform-input-directive/index.ts
showcase/src/app/demo-ui/routes.ts
showcase/src/assets/examples/transform-input-directive/transform-input-directive.html
showcase/src/assets/examples/transform-input-directive/transform-input-directive.ts
showcase/src/assets/translations/en.json
showcase/src/assets/translations/fr.json
showcase/src/assets/translations/nl.json

- added directive `input[starkTransformInput], textarea[starkTransformInput]`
- added partial demo
ISSUES CLOSED: #1099
```
[ ] Bugfix
[x] Feature
```
Issue Number: #1099 
The directive `starkTransformInput` adds the capability to pass a function to an input to transform the input.
```
[ ] Yes
[x] No
```

feat(stark-ui): implement directive to transform input value before passing it to a ngControl

---

showcase/src/app/app.module.ts
starter/src/app/app.module.ts

ISSUES CLOSED: #113
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #113
The `UIRouterModule` in Starter and Showcase is now configured to enable HTML5 Push State always. Before it was enabled based on a condition aimed to support old browsers that don't support HTML5 Push State such as IE lower than 10.
This is no longer relevant since we only targer IE 11 and it does support HTML5 History API.
```
[ ] Yes
[X] No
```

refactor(stark-demo): explicitly enable HTML5 Push State in the config of the UIRouterModule

---

packages/stark-ui/src/modules/table/components/_table.component.scss
packages/stark-ui/src/modules/table/components/column.component.html
packages/stark-ui/src/modules/table/components/column.component.ts
packages/stark-ui/src/modules/table/components/table.component.html
packages/stark-ui/src/modules/table/components/table.component.spec.ts
packages/stark-ui/src/modules/table/components/table.component.ts
packages/stark-ui/src/modules/table/entities.ts
packages/stark-ui/src/modules/table/entities/table-row-actions.intf.ts
showcase/src/app/demo-ui/components/index.ts
showcase/src/app/demo-ui/components/table-regular/table-regular.component.html
showcase/src/app/demo-ui/components/table-regular/table-regular.component.ts
showcase/src/app/demo-ui/components/table-with-fixed-actions/index.ts
showcase/src/app/demo-ui/components/table-with-fixed-actions/table-with-fixed-actions.component.html
showcase/src/app/demo-ui/components/table-with-fixed-actions/table-with-fixed-actions.component.scss
showcase/src/app/demo-ui/components/table-with-fixed-actions/table-with-fixed-actions.component.ts
showcase/src/app/demo-ui/demo-ui.module.ts
showcase/src/app/demo-ui/pages/table/demo-table-page.component.html
showcase/src/assets/examples/table/regular/table.ts
showcase/src/assets/examples/table/with-fixed-actions/table.html
showcase/src/assets/examples/table/with-fixed-actions/table.scss
showcase/src/assets/examples/table/with-fixed-actions/table.ts
showcase/src/assets/translations/en.json
showcase/src/assets/translations/fr.json
showcase/src/assets/translations/nl.json
showcase/src/main.browser.ts
starter/src/main.browser.ts

  - added documentation / demo
```
[ ] Bugfix
[x] Feature
```
Issue Number: #1143 
```
[ ] Yes
[x] No
```

feat(stark-ui): add sticky action column to `stark-table`

---

packages/stark-ui/src/modules/table/components/table.component.spec.ts
packages/stark-ui/src/modules/table/components/table.component.ts

- added test
- refactored test typing
ISSUES CLOSED: #1087
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1087 
The `stark-table` does not fail on undefined data anymore
```
[ ] Yes
[x] No
```

fix(stark-ui): fix table error when `data` not initialized

---

packages/stark-ui/assets/styles/_base.scss
packages/stark-ui/src/modules/app-footer/components/_app-footer.component.scss
packages/stark-ui/src/modules/app-sidebar/components/_app-sidebar.component.scss
showcase/src/app/app.component.html
showcase/src/app/shared/components/table-of-contents/table-of-contents.component.html
showcase/src/app/shared/components/table-of-contents/table-of-contents.component.scss
showcase/src/app/shared/components/table-of-contents/table-of-contents.component.spec.ts
showcase/src/app/shared/components/table-of-contents/table-of-contents.component.ts
starter/src/app/app.component.html

- fix footer overflow
- fix footer hovering above bottom of screen
- removed unused redundant DOM from `app.component.html` (showcase / starter)
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #1169 
Footer sticks to bottom.
```
[x] Yes
[ ] No
```
- `stark-app-sidenav-content` should not be applied to a wrapper element (`div`) anymore. Replace it with a `ng-container`.
This ensures the footer is always at the bottom. (see Starter for an example)

fix(stark-ui): update some component styling to fix bugs

---

.release-it.json
RELEASE.md
build.sh
check-nightly-version.js
check-stark-versions.js
package.json
release-publish.sh

ISSUES CLOSED: #420, #468
```
[X] Bugfix
[ ] Feature
```
Issue Number: #420, #468
- After every release not only the `latest` is set but also the `next` tag (using the [`npm dis-tag`](https://docs.npmjs.com/adding-dist-tags-to-packages#adding-a-dist-tag-to-a-specific-version-of-your-package) ). So they will point to the same version right after releasing (until a new nightly build is created).
- The nightly builds versioning is now based on a "future" version to …

fix(release): set npm tags 'latest' and 'next' correctly after every release. Fix nightly builds versioning

---

build.sh

```
[X] Bugfix
[ ] Feature
```
The changes to the `build.sh` script done in #1185 introduced a bug in Windows:
```
./build.sh: line 146: TRAVIS_EVENT_TYPE: unbound variable
```
The issue is that the `TRAVIS_EVENT_TYPE` variable is not initialized to ensure it exists locally (on Travis it is an environment variable so there is no error there).
A check was added to initialize the variable if it doesn't exist.
```
[ ] Yes
[X] No
```

chore(release): fix 'unbound variable' error in build.sh introduced in #1185

---

showcase/src/app/demo-ui/pages/dialogs/dialogs-page.component.ts

```
[X] Bugfix
[ ] Feature
```
Wrong reference links in the Dialogs demo page created in #1183 
Correct reference links pointing to the corresponding API docs.
```
[ ] Yes
[X] No
```

fix(stark-demo): fix wrong reference links in Dialogs demo page

---

packages/stark-ui/src/modules/date-picker/components/date-picker.component.ts

```
[X] Bugfix
[ ] Feature
```
There was a small bug with the date-picker due to our implementation of MatFormField in #1178. 
When the date-picker was disabled, it was still focusable.
When the date-picker is disabled, it is not focusable anymore.
```
[ ] Yes
[X] No
```

fix(stark-ui): date-picker - disabled stark-date-picker not focusable anymore

---

packages/stark-core/package-lock.json
packages/stark-ui/package-lock.json
showcase/package-lock.json
showcase/src/app/shared/components/table-of-contents/table-of-contents.component.spec.ts

```
[X] Bugfix
[ ] Feature
```
After the automatic upgrade of `@types/jasmine` to v3.3.12, some new violations were reported on the `.spec.ts` files of the Showcase which break the Travis build.
- The new violations are fixed.
- Adapted the `package-lock.json` file in stark-core, stark-ui and showcase to specify the latest version of `@types/jasmine` being used.
```
[ ] Yes
[X] No
```

test(stark-all): fix last TSLint error in Showcase unit tests after upgrade of @types/jasmine to v3.3.12

---

packages/stark-ui/src/modules/pretty-print/components/pretty-print.component.spec.ts

```
[X] Bugfix
[ ] Feature
```
After the automatic upgrade to the latest version of `PrismJS` (1.16.0) one unit test in stark-ui is failing.
The cause is a small change in the new version compared to the previous one (most likely a bug in the previous version).
The failing unit test is fixed in a way that is compatible with the previous and latest versions of `PrismJS`
```
[ ] Yes
[X] No
```

test(stark-ui): adapt failing unit test with latest version of PrismJS (1.16.0)

---

greenkeeper.json
package-lock.json
package.json
packages/stark-core/src/modules/http/builder/http-request-builder.spec.ts
packages/stark-core/src/util/date.util.spec.ts
packages/stark-rbac/base.spec.ts
packages/stark-rbac/karma.conf.ci.js
packages/stark-rbac/karma.conf.js
packages/stark-ui/karma.conf.ci.js
packages/stark-ui/karma.conf.js
packages/stark-ui/src/modules/date-picker/components/date-picker.component.spec.ts
packages/stark-ui/src/modules/date-range-picker/components/date-range-picker.component.spec.ts
showcase/package-lock.json
showcase/package.json
showcase/src/app/demo-ui/pages/date-picker/demo-date-picker-page.component.ts
showcase/src/app/demo-ui/pages/input-mask-directives/demo-input-mask-directives-page.component.ts
showcase/src/app/in-memory-data/interceptors/in-memory-data.interceptor.ts
showcase/src/app/shared/components/table-of-contents/table-of-contents.component.ts
showcase/src/assets/examples/date-picker/ng-model.ts
starter/package.json

ISSUES CLOSED: #1234
```
[ ] Bugfix
[X] Feature
```
Issue Number: #1234 
- upgraded `typescript` to version 3.2.4
- upgraded `@angular/flex-layout` to latest version (7.0.0-beta.24) since it depends on TS 3.2
- removed `@angular/flex-layout` from `greenkeeper.json` exclusions
- fix minor issues due to new deprecations in TypeSscript 3.2 DOM API
- removed some unnecessary types that are inferrable
- added missing RBAC tests in npm `test:ci:all` script
- fixed wrong code …

feat(stark-all): upgrade to TypeScript 3.2 (latest version supported in Angular 7.2)

---

packages/stark-core/src/modules/routing/services/routing.service.spec.ts
packages/stark-ui/src/modules/action-bar/components/action-bar.component.spec.ts
packages/stark-ui/src/modules/app-data/components/app-data.component.spec.ts
packages/stark-ui/src/modules/app-logout/components/app-logout.component.spec.ts
packages/stark-ui/src/modules/date-picker/components/date-picker.component.spec.ts
packages/stark-ui/src/modules/date-range-picker/components/date-range-picker.component.spec.ts
packages/stark-ui/src/modules/generic-search/components/generic-search/generic-search.component.spec.ts
packages/stark-ui/src/modules/language-selector/components/language-selector.component.spec.ts
packages/stark-ui/src/modules/pagination/components/pagination.component.spec.ts
packages/stark-ui/src/modules/session-ui/components/session-card/session-card.component.spec.ts
packages/stark-ui/src/modules/session-ui/pages/login/login-page.component.spec.ts
packages/stark-ui/src/modules/session-ui/pages/preloading/preloading-page.component.spec.ts
packages/stark-ui/src/modules/session-ui/pages/session-expired/session-expired-page.component.spec.ts
packages/stark-ui/src/modules/session-ui/pages/session-logout/session-logout-page.component.spec.ts
packages/stark-ui/src/modules/toast-notification/components/toast-notification.component.spec.ts

ISSUES CLOSED: #1247
```
[X] Bugfix
[ ] Feature
```
Issue Number: #1247 
- No warnings in unit tests.
- All imports in unit tests are relative to the package corresponding to the test instead of importing from the package itself (`import { Foo } from "../entities"` in stark-ui instead of `import { Foo } from "@nationalbankbelgium/stark-ui"`).
- Import Stark components in unit tests instead of Stark modules to clearly identify the dependencies between the different …

test(stark-all): fix minor issues in tests to prevent unwanted warnings. Fix wrong imports

---

packages/stark-ui/src/modules/svg-view-box/directives/svg-view-box.directive.spec.ts
packages/stark-ui/src/modules/svg-view-box/directives/svg-view-box.directive.ts

- updated test
ISSUES CLOSED: #1216
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1216 
`starkSvgViewBox` directive now overwrites the viewBox value of an svg element.
```
[x] Yes
[ ] No
```

fix(stark-ui): overwrite viewBox value when using `starkSvgViewBox` directive

---

package-lock.json
package.json
packages/stark-build/package-lock.json
packages/stark-build/package.json
packages/stark-core/package.json
packages/stark-rbac/package.json
packages/stark-ui/package.json
packages/stark-ui/src/modules/progress-indicator/entities/progress-indicator-full-config.entity.intf.ts

Closes #1251 
```
[ ] Bugfix
[ ] Feature
```
Current version: 9.10.1
- Updated to the latest version: 10.0.1
- Fixed breaking change from Stylelint 10.x in stark packages by adding the `--allow-empty-input` option in the `lint-css` npm scripts.
```
[ ] Yes
[X] No
```

Greenkeeper/stark packages/stylelint 10.0.1

---

packages/stark-core/src/modules/http/repository/http-abstract-repository.ts
packages/stark-core/src/modules/user/entities.ts
packages/stark-core/src/modules/user/entities/user-module-config.entity.intf.ts
packages/stark-core/src/modules/user/repository/user.repository.spec.ts
packages/stark-core/src/modules/user/repository/user.repository.ts
packages/stark-core/src/modules/user/services/user.service.intf.ts
packages/stark-core/src/modules/user/services/user.service.ts
packages/stark-core/src/modules/user/user.module.ts

ISSUES CLOSED: #956
```
[ ] Bugfix
[X] Feature
```
Issue Number: #956 
- a config object can be passed to the User Module to set the User profile resource path to be used by the User Repository
- a new `STARK_USER_PROFILE_RESOURCE_PATH` injection token is created to pass the custom resource path along to the User Repository
- implement missing unit tests for the User Repository
```
[ ] Yes
[X] No
```

feat(stark-core): allow configuring the User profile resource path used by the User Repository

---

packages/stark-build/config/tslint.json

```
[X] Bugfix
[ ] Feature
```
All PR's from Greenkeeper are failing now: https://travis-ci.org/NationalBankBelgium/stark/builds
Issue Number: ReactiveX/rxjs#4723
As a temporary fix, the `deprecation` TSLint rule is disabled to prevent all Greenkeeper PR's from failing.
The rule should be re-enabled once the issue on RxJS typings is solved.
```
[ ] Yes
[X] No
```

build(stark-all): disable TSLint 'deprecation' rule as a temporary fix for a bug in RxJS 6.5 typings: ReactiveX/rxjs#4723

---

packages/stark-ui/src/modules/date-picker/components/date-picker.component.spec.ts
packages/stark-ui/src/modules/date-picker/components/date-picker.component.ts
showcase/src/app/demo-ui/pages/date-picker/demo-date-picker-page.component.html
showcase/src/assets/examples/date-picker/ng-model.html
showcase/src/assets/examples/date-picker/reactive-form.html

ISSUES CLOSED #1255, #1257
```
[X] Bugfix
[ ] Feature
```
Issue Number: #1255, #1257
- the asterisk (*) is appended to the date picker label in case it is marked as required
- in case the date picker is initialized with an invalid date, it will only be displayed as invalid until the user interacts with the picker.
- refactored the unit tests to make them more readable
```
[ ] Yes
[X] No
```

Bugfix/date picker invalid status on initialization + required asterisk not shown

---

packages/stark-ui/assets/styles/_base.scss

```
[x] Bugfix
[ ] Feature
```
When the view width gets below 1100px the `.stark-main-container` sizes on content width, creating a lot of white space and inconsistent design across different pages.
Scales better.
```
[x] Yes
[ ] No
```

fix(stark-ui): properly size `.stark-main-container` on different screen sizes

---

packages/stark-ui/src/modules/input-mask-directives/directives/timestamp-mask.directive.ts
packages/stark-ui/src/modules/input-mask-directives/directives/timestamp-pipe.fn.spec.ts
packages/stark-ui/src/modules/input-mask-directives/directives/timestamp-pipe.fn.ts
showcase/src/app/app.module.ts
showcase/src/app/shared/shared.module.ts
showcase/src/app/translation.config.ts
starter/src/app/app.module.ts
starter/src/app/home/home.module.ts
starter/src/app/translation.config.ts

ISSUES CLOSED: #1260 
```
[X] Bugfix
[ ] Feature
```
Issue Number: #1260
- now when deleting a character, the mask keeps the position as empty instead of moving the characters backwards so the user can safely type in the new character. This prevents the date picker from getting weird date values. The `keepCharPositions` option is now enabled in the timestamp directive (see https://github.com/text-mask/text-mask/blob/master/componentDocumentation.md#keepcharpositions)
- …

Bugfix/date picker mask weird behavior + inconsistent date picker locale in Showcase and Starter

---

packages/stark-build/tsconfig.json

```
[ ] Bugfix
[ ] Feature
```
Since the TypeScript configuration used in Stark will be moved to a separate package: https://github.com/NationalBankBelgium/code-style. It is important to update/enhance our TypeScript compilation rules to make sure we keep those that are really relevant for our packages.
All the [strict type checking options](https://github.com/microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#new---strict-master-option) are now enabled:
- …

feat(stark-build): enable all strict type checking options in tsconfig.json file. Remove obsolete options

---

packages/stark-ui/src/modules/table/components/_table.component.scss
packages/stark-ui/src/modules/table/components/table.component.html
packages/stark-ui/src/modules/table/components/table.component.spec.ts
packages/stark-ui/src/modules/table/components/table.component.ts
showcase/src/app/demo-ui/components/table-regular/table-regular.component.html
showcase/src/app/demo-ui/components/table-with-fixed-header/table-with-fixed-header.component.html
showcase/src/app/demo-ui/components/table-with-fixed-header/table-with-fixed-header.component.ts
showcase/src/assets/examples/table/regular/table.html
showcase/src/assets/examples/table/with-fixed-header/table.html
showcase/src/assets/examples/table/with-fixed-header/table.ts

ISSUES CLOSED: #1244 
```
[ ] Bugfix
[X] Feature
```
There is no rows counter available in the table component.
It was the case in the previous implementation of Stark.
Issue Number: #1244
Provide optional rows counter in the table component.
```
[ ] Yes
[X] No
```
@christophercr I hesitate about the number to show...
Here, I display `{{ data.length }}`, as it was the case in the previous implementation, but we could display `{{ dataSource.data.length }}` which …

feat(stark-ui): table - Add support to show rows counter

---

packages/stark-ui/src/modules/table/components/_table-theme.scss
packages/stark-ui/src/modules/table/components/_table.component.scss
packages/stark-ui/src/modules/table/components/table.component.html
packages/stark-ui/src/modules/table/components/table.component.spec.ts

ISSUES CLOSED: #1303
```
[ ] Bugfix
[X] Feature
```
Issue Number: #1303 
The icon of the global filter now changes color whenever the filter is enabled so the user knows that the filtered is being applied.
```
[ ] Yes
[X] No
```

feat(stark-ui): change color of global filter icon to indicate when the global filter is enabled

---

showcase/ghpages-adapt-bundle-urls.js

ISSUES CLOSED: #1328
```
[X] Bugfix
[ ] Feature
```
Issue Number: #1328 
The script to replace the placholders for the actual baseHref and deployUrl is adapted to replace the placeholders `<stark-dummy-base-href>` and `<stark-dummy-deploy-url>` in any JS and CSS file apart from `index.html`.
```
[ ] Yes
[X] No
```

fix(stark-demo): enhance script to replace baseHref and deployUrl in any JS and CSS file in Showcase when deploying to GhPages

---

packages/stark-ui/src/modules/dropdown/components/dropdown.component.spec.ts
packages/stark-ui/src/modules/dropdown/components/dropdown.component.ts

ISSUES CLOSED: #1364
```
[X] Bugfix
[ ] Feature
```
Change the dropdown setDisabledState function to take into account the emitEvent.
Issue Number: #1364 
```
[ ] Yes
[X] No
```

fix(stark-ui): ui dropdown: not taking into account option - emitEvent

---

packages/stark-ui/src/modules/table/components/table.component.html
packages/stark-ui/src/modules/table/components/table.component.spec.ts
packages/stark-ui/src/modules/table/components/table.component.ts
showcase/src/app/demo-ui/components/table-with-selection/table-with-selection.component.html
showcase/src/app/demo-ui/components/table-with-selection/table-with-selection.ts
showcase/src/assets/examples/table/with-selection/table.html
showcase/src/assets/examples/table/with-selection/table.ts

ISSUES CLOSED: #1366
Disabled changeDetection strategy in Stark Table from 'OnPush' to 'Default' in order to
fix selection issues.
```
[X] Bugfix
[X] Feature
```
The developer cannot manage the Stark Table selection programmatically.
Issue Number: #1366 
New `selection` Input has been added to allow the developer to obtain all the features proposed by the `selection` model object provided by/in angular/material. 
```
[ ] Yes
[X] No
```

feat(stark-ui): table - add support for angular CDK selection model

---

packages/stark-ui/assets/styles/_material-fixes.scss

The default layout of inputs causes some letters (gj...) to be cut off at the bottom.
ISSUES CLOSED: #1374
Change the default layout of inputs.
```
[X] Bugfix
[ ] Feature
```
The default layout of inputs causes some letters (gj...) to be cut off at the bottom.
Issue Number: #1374
The default layout of inputs doesn't cut off some letters anymore.
```
[ ] Yes
[X] No
```

fix(stark-ui): reset line-height of <input/> to avoid letters to be cut off at the bottom

---

packages/stark-ui/src/modules/app-data/components/_app-data.component.scss

In the AppData in 'dropdown' mode, when the 'summary' pane is too big, it is overlapped by the
'detail' pane so the summary content is not fully visible
ISSUES CLOSED: #1341
The 'summary' pane isn't overlapped anymore.
```
[X] Bugfix
[ ] Feature
```
Issue Number: #1341 
```
[ ] Yes
[X] No
```

fix(stark-ui): ui: app-data - in 'dropdown' mode the 'detail' pane overlaps the 'summary'

---

packages/stark-ui/src/modules/table/components/column.component.html
packages/stark-ui/src/modules/table/components/column.component.ts
packages/stark-ui/src/modules/table/components/table.component.html
packages/stark-ui/src/modules/table/components/table.component.spec.ts
packages/stark-ui/src/modules/table/components/table.component.ts
packages/stark-ui/src/modules/table/entities/table-column-filter.intf.ts
packages/stark-ui/src/modules/table/entities/table-filter.intf.ts
showcase/src/app/demo-ui/components/table-regular/table-regular.component.ts

ISSUES CLOSED: #1352
```
[ ] Bugfix
[X] Feature
```
In column filtering, there is a little popup screen to type the filter-characters. Now it opens under the column header, which makes it difficult to see the results of the filter.
Issue Number: #1352
Open it above the column header instead.
```
[ ] Yes
[X] No
```

feat(stark-ui): put the column filter of the table above the title

---

packages/stark-ui/src/modules/table/components/table.component.spec.ts
packages/stark-ui/src/modules/table/components/table.component.ts

ISSUES CLOSED: #1392
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1392 
only the available rows are selected / emitted
```
[ ] Yes
[x] No
```

fix(stark-ui): select only available rows with select all on table

---

packages/stark-core/src/modules/routing/services/routing.service.spec.ts
packages/stark-core/src/modules/session/services/session.service.spec.ts
packages/stark-core/src/modules/xsrf/services/xsrf.service.spec.ts
packages/stark-rbac/src/modules/authorization/services/authorization.service.spec.ts
packages/stark-testing/package-lock.json
packages/stark-testing/package.json
packages/stark-ui/src/modules/app-logout/components/app-logout.component.spec.ts
packages/stark-ui/src/modules/date-picker/components/date-picker.component.spec.ts
packages/stark-ui/src/modules/minimap/components/minimap.component.spec.ts
packages/stark-ui/src/modules/progress-indicator/directives/progress-indicator.directive.spec.ts
showcase/package-lock.json

```
[X] Bugfix
[ ] Feature
```
After the automatic upgrade of `@types/jasmine` to v3.4.x, some TS compilation issues were reported on our `.spec.ts` files which break the Travis builds triggered by Greenkeeper.
See: https://travis-ci.org/NationalBankBelgium/stark/builds/590105818
- The new violations are fixed.
- Adapted the `package.json` file in stark-testing to specify the latest version of `@types/jasmine` being used and to replace the caret range by a tilde range …

test(stark-all): fix wrong types in unit tests after automatic upgrade of @types/jasmine to v3.4.X

---

showcase/src/app/demo-ui/components/table-regular/table-regular-theme.scss
showcase/src/app/demo-ui/components/table-regular/table-regular.component.ts
showcase/src/styles/_theme.scss
showcase/src/styles/styles.scss

ISSUES CLOSED: #1311 
```
[X] Bugfix
[ ] Feature
```
Issue Number: #1311 
The styles for the `TableRegularComponent` are now global styles instead of encapsulated styles because they depend on the Angular Material theming (which is also defined globally).
So now running `npm run ngc` in the showcase doesn't throw any error.
```
[ ] Yes
[X] No
```

fix(stark-demo): replace encapsulated styles of Table Regular Component by global styles since they depend on Angular Material theming

---

packages/stark-core/src/modules/logging/services/logging.service.spec.ts
packages/stark-core/src/modules/logging/services/logging.service.ts

ISSUES CLOSED: #1319
```
[X] Bugfix
[ ] Feature
```
Issue Number: #1319 
The HTTP request triggered to flush the logs to the backend now also contains the `correlation-id` header with the correspondent value.
```
[ ] Yes
[X] No
```

fix(stark-core): add missing correlation-id header in the HTTP request sent to flush the logs

---

packages/stark-ui/src/modules/table/components/table.component.spec.ts

```
[ ] Bugfix
[ ] Feature
```
In the unit tests of the `StarkTable` component the logging is polluted with many errors like this:
```
LOG: 'Error retrieving icon: Unable to find icon with the name ":xxx"'
```
For example: https://travis-ci.org/NationalBankBelgium/stark/jobs/611922573
Although those errors don't represent an actual issue in the functionality, they make the logging to become quite polluted with this kind of "errors" making them difficult to read and …

test(stark-ui): fix Table Component unit tests to avoid logging of 'Unable to find icon...' error

---

packages/stark-ui/src/modules/table/components/table.component.html
packages/stark-ui/src/modules/table/components/table.component.spec.ts

ISSUES CLOSED: #1462
```
[X] Bugfix
[ ] Feature
```
If no row actions are defined, the Stark Table component displays the **Actions** column.
Issue Number: #1462 
If no row actions are defined, the Stark Table component does **not** display the **Actions** column.
```
[ ] Yes
[X] No
```

fix(stark-ui): table actions column is not displayed anymore if no row actions are defined

---

packages/stark-ui/src/modules/table/components/column.component.ts
packages/stark-ui/src/modules/table/components/table.component.spec.ts

ISSUES CLOSED: #1465
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1465
`cellFormatter` is now triggered even if the `rawValue` is undefined.
```
[ ] Yes
[x] No
```

fix(stark-ui): cellFormatter is now called even when the rawValue is undefined

---

packages/stark-ui/src/modules/pagination/components/pagination-config.intf.ts
packages/stark-ui/src/modules/pagination/components/pagination.component.html
packages/stark-ui/src/modules/pagination/components/pagination.component.ts
packages/stark-ui/src/modules/table/components/table.component.ts
showcase/src/app/demo-ui/components/index.ts
showcase/src/app/demo-ui/components/table-with-items-per-page-selector/index.ts
showcase/src/app/demo-ui/components/table-with-items-per-page-selector/table-with-items-per-page-selector.component.html
showcase/src/app/demo-ui/components/table-with-items-per-page-selector/table-with-items-per-page-selector.component.ts
showcase/src/app/demo-ui/demo-ui.module.ts
showcase/src/app/demo-ui/pages/table/demo-table-page.component.html
showcase/src/assets/examples/table/with-items-per-page-selector/table.html
showcase/src/assets/examples/table/with-items-per-page-selector/table.ts
showcase/src/assets/translations/en.json
showcase/src/assets/translations/fr.json
showcase/src/assets/translations/nl.json

ISSUES CLOSED: #1248
```
[ ] Bugfix
[X] Feature
```
Issue Number: #1248
It is now possible to display the `items per page` dropdown in the pagination also on "compact" mode. Since the Table component displays the Pagination component on compact "mode", this change allows the developers to display the "items per page" dropdown in the table by setting `itemsPerPageIsPresent: true` in the pagination config. 
```
[ ] Yes
[X] No
```

feat(stark-ui): add support for displaying the "items per page" dropdown also in Pagination on "compact" mode

---

packages/karma.conf.ci.js
packages/karma.conf.js
packages/stark-core/karma.conf.ci.js
packages/stark-core/karma.conf.js
packages/stark-rbac/karma.conf.ci.js
packages/stark-rbac/karma.conf.js
packages/stark-ui/karma.conf.ci.js
packages/stark-ui/karma.conf.js
showcase/karma.conf.ci.js
showcase/karma.conf.js

ISSUES CLOSED: #1145
```
[ ] Bugfix
[ ] Feature
```
The custom karma configuration for packages is repeated in every stark packages (stark-core, stark-rbac, stark-ui). It's complex to maintain and require to change the Karma config in 3 locations, for now, everytime a change is needed.
The showcase contains useless custom aliases.
Issue Number: #1145 
Karma configurations for packages has been simplified and are written only once under "packages/karma.conf.js" and …

test(stark-all): simplify karma configuration in stark-* packages + showcase

---

packages/stark-ui/src/modules/table/components/dialogs/multisort.component.html

```
[X] Bugfix
[ ] Feature
```
The Multisort dialog tries to display the label property of the column and not the headerlabel property.
Issue Number: #1397
The displayed columns in the Multisort dialog is the headerlabel instead of the name (corresponding to the column header in the table...)
```
[ ] Yes
[x] No
```

fix(stark-ui): change the Multisort component to display the label instead of the column

---

packages/stark-build/config/webpack-partial.common.js

ISSUES CLOSED: #1483
```
[X] Bugfix
[ ] Feature
```
Incorrect warning is present in console due to prettier.
Issue Number: #1483
The warning about `prettier/typescript` is not present anymore.
```
[ ] Yes
[X] No
```

fix(stark-build): fix prettier - Module not found: Error: Can't resolve '@microsoft/typescript-etw'

---

packages/stark-ui/src/modules/table/components/column.component.html
packages/stark-ui/src/modules/table/components/column.component.ts

ISSUES CLOSED: #1478
```
[X] Bugfix
[ ] Feature
```
Issue Number: #1478 
Multisort issue fixed. Also aligned the default value for `sortPriority` in column.component and table.component to the value `100`.
```
[ ] Yes
[X] No
```

fix(stark-ui): table - Multisort - fix order issue when adding/removing sort criteria

---

gh-deploy.sh

ISSUES CLOSED: #1485
```
[X] Bugfix
[ ] Feature
```
The node_version expected by the "gh-deploy.sh" script is **8**.
We forgot to change the expected node version when we removed support for Node 8 in #1447 
Issue Number: #1485 
The expected node_version is **10**.
```
[ ] Yes
[X] No
```

fix(build-main): changed expected node version to 10 in gh-deploy script

---

packages/stark-ui/src/modules/route-search/components/route-search.component.spec.ts
packages/stark-ui/src/modules/route-search/components/route-search.component.ts

ISSUES CLOSED: #1335
```
[ ] Bugfix
[X] Feature
```
There is no support for partial matching in `StarkRouteSearchComponent`.
Issue Number: #1335 
The route-search component now supports the partial matching.
Typing 'logou' proposes the route 'App Logout'.
```
[ ] Yes
[X] No
```

feat(stark-ui): route-search - add support for partial matching

---

packages/stark-ui/src/modules/app-data/app-data.module.ts
packages/stark-ui/src/modules/app-data/components/_app-data-theme.scss
packages/stark-ui/src/modules/app-data/components/_app-data.component.scss
packages/stark-ui/src/modules/app-data/components/app-data.component.html
packages/stark-ui/src/modules/app-data/components/app-data.component.spec.ts
packages/stark-ui/src/modules/app-data/components/app-data.component.ts

rewrite component to use mat-menu instead of custom implementation
ISSUES CLOSED: #1555
```
[X] Bugfix
[ ] Feature
```
Issue Number: #1555 
Issues with the detail-slot have been resolved thanks to a rewrite of the app-data component.
```
[ ] Yes
[X] No
```
~For an unknown reason, in DEV mode, when clicking multiple times quickly on the arrow button to open the detail, the following error is triggered:~
```
Error: ExpressionChangedAfterItHasBeenCheckedError: Expression …
```

 fix(stark-ui): app-data - fixed issues with detail-slot not displayed correctly on small screens

---

packages/stark-ui/src/modules/app-sidebar/components/_app-sidebar.component.scss
packages/stark-ui/src/modules/app-sidebar/components/app-sidebar.component.html
packages/stark-ui/src/modules/app-sidebar/components/app-sidebar.component.ts

ISSUES CLOSED: #1338
```
[X] Bugfix
[ ] Feature
```
The header is not displayed on iOS devices (iTouch, iPhone, iPad). 
Issue Number: #1338 
Adding a new class `stark-ios-device` on `<mat-sidenav-content>` when the device is running on iOS.
Using this class, we remove the fact that the scrollbar which is displayed below the header like here:
Thanks to that the header is displayed correctly on iOS devices. 
Unfortunately the scrollbar takes all the screen and if the …

fix(stark-ui): app-sidebar - header is now visible on iOS devices (iTouch, iPhone, iPad)

---

packages/stark-ui/src/modules/session-ui/effects/session-timeout-warning.effect.spec.ts
packages/stark-ui/src/modules/session-ui/effects/session-timeout-warning.effects.ts

```
[X] Bugfix
[ ] Feature
```
When the Session Timeout Warning Dialog appears, clicking outside the dialog hides the dialog but does not stop the countdown. So the user is disconnected automatically at the end of the countdown. 
Issue Number: #1561 
Clicking outside of the dialog does not do anything. Like this, the user cannot close the dialog due to a wrong manipulation.
```
[ ] Yes
[X] No
```

fix(stark-ui): session - prevent click outside the Session Timeout Warning Dialog

---

package-lock.json
packages/stark-build/package-lock.json
packages/stark-core/package-lock.json
packages/stark-rbac/package-lock.json
packages/stark-testing/package-lock.json
packages/stark-ui/package-lock.json

Update package-lock.json files in:
- root folder
- stark-build
- stark-testing
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Update dependencies
```
The dependencies "@types/lodash" and "@angular/*" are outdated in "package-lock.json" files in the Stark packages and in the root folder.
Updated package-lock.json files in the Stark packages and in the root folder.
```
[ ] Yes
[X] No
```

chore(deps): bump @types/lodash from 4.14.146 to 4.14.149 in stark-core, stark-rbac and stark-ui

---

packages/stark-ui/src/modules/table/components/column.component.html
packages/stark-ui/src/modules/table/components/column.component.ts
packages/stark-ui/src/modules/table/components/table.component.html
packages/stark-ui/src/modules/table/components/table.component.ts
packages/stark-ui/src/modules/table/entities/column-properties.intf.ts
showcase/src/app/demo-ui/components/index.ts
showcase/src/app/demo-ui/components/table-with-footer/index.ts
showcase/src/app/demo-ui/components/table-with-footer/table-with-footer.component.html
showcase/src/app/demo-ui/components/table-with-footer/table-with-footer.component.scss
showcase/src/app/demo-ui/components/table-with-footer/table-with-footer.component.ts
showcase/src/app/demo-ui/demo-ui.module.ts
showcase/src/app/demo-ui/pages/table/demo-table-page.component.html
showcase/src/assets/examples/table/with-footer/table.html
showcase/src/assets/examples/table/with-footer/table.scss
showcase/src/assets/examples/table/with-footer/table.ts
showcase/src/assets/translations/en.json
showcase/src/assets/translations/fr.json
showcase/src/assets/translations/nl.json

ISSUES CLOSED: #1540
Implement a footer for the table component
```
[ ] Bugfix
[X] Feature
```
Issue Number: #1540 
```
[ ] Yes
[X] No
```

feat(stark-ui): add footer to table component

---

packages/stark-ui/src/modules/date-time-picker/components/date-time-picker.component.html
packages/stark-ui/src/modules/date-time-picker/components/date-time-picker.component.scss
packages/stark-ui/src/modules/date-time-picker/components/date-time-picker.component.spec.ts

ISSUES CLOSED: #1430
```
[X] Bugfix
[ ] Feature
```
Issue Number: #1430 
The "clear' button (X) is now be placed correctly to the right next to the date time picker field also in Internet Explorer 11 (apart from all major browsers: Chrome, Edge and Firefox):
```
[ ] Yes
[X] No
```

fix(stark-ui): enhance styling of date time picker component to display the 'clear' button correctly aligned in IE 11

---

README.md
showcase/e2e/protractor.browserstack.conf.js

Received support from BrowserStack and applied their sample config:
https://gist.github.com/HeenaNanwaniGit/52fe377a355077be653e056508d0b271
Added a `localIdentifier` in the `commonCapabilities` and in the options passed to
the `bs_local.start` function in protrator.browserstack configuration.
```
[X] Bugfix
[ ] Feature
```
Sometimes, tests are failing because of an issue with the tests executed in BrowserStack. It happens randomly.
I contacted the …

ci(showcase): fix BrowserStack randomly failing test by adding a `localIdentifier`

---

packages/stark-ui/src/modules/table/components/table.component.ts

ISSUES CLOSED: #1644
```
[X] Bugfix
[ ] Feature
```
Cannot build a library based on `stark-ui`.
Issue Number: #1644
Can build a library based on `stark-ui`.
```
[ ] Yes
[X] No
```

fix(stark-ui): remove wrong `@internal` decorator on `_globalFilterFormCtrl` in table component

---

packages/stark-ui/src/modules/session-ui/routes.ts
packages/stark-ui/src/modules/session-ui/session-ui.module.spec.ts

ISSUES CLOSED: #1570
```
[X] Bugfix
[ ] Feature
```
Issue Number: #1570 
All overlays created by the `mat-select` component from the `StarkDropdown` and `mat-menu` from the `StarkActionBar` and other star components are now removed when navigating to an exit state (`StarkSessionEspired` and `StarkSessionLogout`) by destroying the container where all of them are rendered
```
[ ] Yes
[X] No
```

fix(stark-ui): remove all overlays by destroying the Angular CDK OverlayContainer when navigating to an 'exit' state

---

.dependabot/config.yml
packages/stark-ui/package-lock.json
packages/stark-ui/package.json

This reverts commit 3ac874e6164542e1180007fc56ab813e03dc219e.
ISSUES CLOSED: #1762
```
[X] Bugfix
[ ] Feature
```
Wrong update of `@mdi/angular-material` dependency.
Issue Number: #1762 
Revert wrong commit.
```
[ ] Yes
[X] No
```

Revert "chore(deps): bump @mdi/angular-material in /packages/stark-ui"

---

packages/stark-ui/src/modules/table/components/column.component.html
packages/stark-ui/src/modules/table/components/table.component.html
packages/stark-ui/src/modules/table/components/table.component.spec.ts
packages/stark-ui/src/modules/table/components/table.component.ts
packages/stark-ui/src/modules/table/directives/table-row-content.directive.ts
packages/stark-ui/src/modules/table/table.module.ts
showcase/src/app/demo-ui/components/index.ts
showcase/src/app/demo-ui/components/table-with-custom-cell-rendering/index.ts
showcase/src/app/demo-ui/components/table-with-custom-cell-rendering/table-with-custom-cell-rendering.component.html
showcase/src/app/demo-ui/components/table-with-custom-cell-rendering/table-with-custom-cell-rendering.component.ts
showcase/src/app/demo-ui/demo-ui.module.ts
showcase/src/app/demo-ui/pages/table/demo-table-page.component.html
showcase/src/assets/examples/table/with-custom-cell-rendering/table.html
showcase/src/assets/examples/table/with-custom-cell-rendering/table.ts
showcase/src/assets/translations/en.json
showcase/src/assets/translations/fr.json
showcase/src/assets/translations/nl.json

```
[ ] Bugfix
[X] Feature
```
For now it's impossible to put html inside a cell of a table. Only text is allowed.
The render of a cell in table is now fully customisable. 
```
[ ] Yes
[X] No
```

feat(stark-ui): add the possibility to custom the rendering of a cell in tables

---

.travis.yml

```
[X] Bugfix
[ ] Feature
```
Travis CI does not work for starter in NodeJS 10.
Issue Number: #2488 
Travis CI should work if no code issue.
```
[ ] Yes
[X] No
```

ci(starter): disable starter integration in Travis-CI builds

---

.cz-config.js
.github/workflows/build.yml
.travis.yml
README.md
build.sh
combine-packages-coverage.js
docs/E2E_TESTING.md
docs/GITHUB_ACTIONS.md
package.json
packages/stark-build/README.md
packages/stark-core/README.md
packages/stark-rbac/README.md
packages/stark-testing/README.md
packages/stark-ui/README.md
scripts/ci/_ghactions-group.sh
scripts/ci/print-gh-logs.sh
showcase/e2e/protractor.browserstack.conf.js

Set BrowserStack configuration in GitHub Actions instead of Travis-CI
```
[ ] Bugfix
[X] Feature
```
We encounter issues with Travis (especially with BrowserStack and starter).
We would like to replace Travis CI by GitHub Actions but we are not ready yet (because not fully tested).
We add GitHub Actions next to Travis and we keep all the release process in Travis (we don't break anything right now 😊)
```
[ ] Yes
[X] No
```
The result is available on …

ci(stark-all): add support for GitHub Actions

---

.github/workflows/build.yml

Secrets required to use BrowserStack actions are not accessible during build of pull request.
```
[X] Bugfix
[ ] Feature
```
GitHub Actions CI does not work currently for PRs across forks. Secrets `BROWSERSTACK_ACCESS_KEY` and `BROWSERSTACK_USERNAME` are not accessible during build of a Pull Request from a fork.
Temporary disable BrowserStack check for pull request. A final solution should be implemented later.
It will probably be based on …

ci(stark-all): temporary disable BrowserStack for Pull Requests

---

README.md
packages/stark-build/README.md
packages/stark-core/README.md
packages/stark-rbac/README.md
packages/stark-testing/README.md
packages/stark-ui/README.md
showcase/README.md
starter/README.md

```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: README changes
```
Travis-ci links points to travis-ci.org (old) instead of travis-ci.com (new).
ALso, David-dm platform seems not stable and often, we have the following icons appearing in README file:
Adapted travis-ci URLs to use travis-ci.com
Using shields.io icons instead of travis-ci and david-dm ones 😊 
```
[ ] Yes
[X] No
```
It comes with more colored badges 👍

Fix travis npm GitHub actions links

---

packages/stark-core/package-lock.json
packages/stark-core/package.json

class-validator > 0.12.0 contains some breaking changes.
```
[X] Bugfix
[ ] Feature
```
stark-core is using `"class-validator": "^0.9.1"`, meaning is currently using the version 0.13.0 which contains some breaking changes.
"class-validator" dependency is fixed to version "0.11.0" which does not contain important breaking changes.
"class-validator" will be updated to the latest version, currently 0.13.0, in Stark 11. 
```
[ ] Yes
[X] No
```

fix(stark-core): fix "class-validator" dependency to version ~0.11.0

---

packages/stark-core/tslint.json
packages/stark-rbac/tslint.json
packages/stark-ui/tslint.json
showcase/tslint.json
starter/package.json
starter/tslint.json

```
[ ] Bugfix
[ ] Feature
```
We have the following custom "typecheck" rule in tslint config of all modules in Stark. 
```
"typedef": [true, "call-signature", "parameter", "arrow-parameter", "property-declaration"]
```
Due to code-style upgrade (v1.5.0), the custom rule has been removed in favor of the default one in code-style library:
```
"typedef": [true, "call-signature", "parameter",  "property-declaration"]
```
```
[ ] Yes
[X] No
```

refactor(stark-all): remove custom "typecheck" rule in tslint configuration after code-style upgrade

---

packages/stark-core/src/modules/logging/services/logging.service.ts

As Stark does not use returned body when persisting logs, there is no need to force the backend
to send a 201 status code. The 204 status code should be accepted when no content is received.
```
[X] Bugfix
[ ] Feature
```
When persisting logs, Stark does not use response body. For utility resources as logging, Stark should accept 204 http status code in response.
Stark logging service accept http 204 "no content" status code. 
```
[ ] Yes
[X] No
```

fix(stark-core): add support for http 204 status code when persisting logs

---

.github/dependabot.yml

Due to centralization of dependencies into root folder and no longer in packages/stark-* folders,
the max number of PRs should be increased to accept enough PRs for root dependencies.
```
[ ] Bugfix
[ ] Feature
```
Dependabot cannot create enough PRs for root folder after centralization of dependencies into root folder.
Dependabot can create 40 PRs in parallel for root folder
```
[ ] Yes
[X] No
```

ci(stark-all): increase max PR number that Dependabot can create

---

packages/stark-ui/src/modules/date-picker/components/date-picker.component.ts
packages/stark-ui/src/modules/date-time-picker/components/date-time-picker.component.ts

Modifying formControl value after destroying `stark-date-picker` or `stark-datetime-picker`
components triggers the following error:
`Error: ViewDestroyedError: Attempt to use a destroyed view: detectChanges`
ISSUES CLOSED: #2874
```
[X] Bugfix
[ ] Feature
```
Issue Number: #2874
Stop calling `cdRef.detectChanges()` in `set value()` methods in date-picker and date-time-picker components.
```
[ ] Yes
[X] No
```

fix(stark-ui): fix `ViewDestroyedError` issue linked to formControl usage

---

.github/workflows/build.yml

```
[ ] Bugfix
[ ] Feature
```
Releasing a new 10.2.x version of Stark does not work due to an issue with docs generation in CI.
Releasing a new 10.2.x version of Stark does no longer generate docs.
```
[ ] Yes
[X] No
```

ci(release): stop publishing docs in 10.2.x branch during release

---

.github/workflows/build.yml

ISSUES CLOSED: #2902
```
[X] Bugfix
[ ] Feature
```
Issue Number: #2902
Allow failures in macos build workflow 
```
[ ] Yes
[X] No
```

ci(build-main): mark macos runners as experimental and allow failures on these runners

---

packages/stark-core/tsconfig.json
packages/stark-rbac/tsconfig.json
packages/stark-ui/tsconfig.json

See ng-packagr/ng-packagr#2056 for more details
```
[X] Bugfix
[ ] Feature
```
When we build Stark packages, we receive lots of warnings.
For instance, we have this when we build `stark-core`:
```bash
------------------------------------------------------------------------------
Building entry point '@nationalbankbelgium/stark-core'
------------------------------------------------------------------------------
✔ Compiling with Angular sources in Ivy partial compilation …
```

fix(stark-all): disable `emitDecoratorMetadata` in tsconfig of stark-* packages in order to solve build warnings

---

packages/stark-core/src/modules/xsrf/services/xsrf-config.intf.ts
packages/stark-core/src/modules/xsrf/services/xsrf.service.spec.ts
packages/stark-core/src/modules/xsrf/services/xsrf.service.ts

Add `httpOnly` property in `StarkXSRFConfig` that can be passed to `StarkXSRFModule.forRoot()`
ISSUES CLOSED: #3136
```
[X] Bugfix
[X] Feature
```
Issue Number: #3136
Add support for `httpOnly` cookie thanks to the new `httpOnly` property in `StarkXSRFConfig`
```
[ ] Yes
[X] No
```

feat(stark-core): add support for `httpOnly` cookie in `StarkXSRFService`

---

.github/workflows/dependabot-sync-stark-dependencies.yml

```
[X] Bugfix
[ ] Feature
```
Dependabot PRs are failing due to broken "dependabot-sync-stark-dependencies" workflow.
"dependabot-sync-stark-dependencies" workflow commits now with `--no-verify` argument in order to bypass issue.
Since the workflow simply updates the package.json and package-lock.json files, it is not necessary to run the checks when committing in the workflow.
```
[ ] Yes
[X] No
```

ci(stark-all): fix dependabot-sync-stark-dependencies workflow with `--no-verify` argument

---

packages/stark-ui/src/modules/table/components/table.component.html
packages/stark-ui/src/modules/table/components/table.component.spec.ts

When changing language we got an issue with the name of the column for the Actions in NL
Test are
updated as well.
ISSUES CLOSED: #3391
```
[x] Bugfix
[ ] Feature
```
Issue Number: #3391 
```
[ ] Yes
[x] No
```

fix(stark-ui): fix issue with table on action #3391

---

package.json

```
[X] Bugfix
[ ] Feature
```
Cannot use `npm run commit` command on Windows. 
```shell
$ npm run commit
> stark-srcr@10.2.0 commit
> ./node_modules/.bin/git-cz
'.' is not recognized as an internal or external command,
operable program or batch file.
```
Can use `npm run commit` command on Windows, Mac and Linux
```
[ ] Yes
[X] No
```

fix(build-main): fix `npm run commit` script in order to fix the usage on Windows OS

---

packages/stark-ui/src/modules/table/components/table.component.html
packages/stark-ui/src/modules/table/components/table.component.spec.ts

When changing language we got an issue with the name of the column for the Actions in NL
ISSUES CLOSED: #3391
```
[x] Bugfix
[ ] Feature
```
Issue Number: 3391
```
[ ] Yes
[x] No
```

fix(stark-ui): fix issue with table on action

---

.github/workflows/build.yml

MacOS jobs are always failing due to a GitHub limitation when downloading the GeckoDriver from GitHub for `Protractor`
```
[X] Bugfix
[ ] Feature
```
All the plans running on macos runners are failing due to a download, by Protractor, of GeckoDriver on GitHub.
It hits an API rate limit of GitHub: https://github.com/actions/runner-images/issues/602
We can easily see if a PR is ok if no failed jobs.
```
[ ] Yes
[X] No
```

ci(build-main): disable failing MacOS runners

---

packages/stark-ui/src/modules/toast-notification/components/_toast-notification.component.scss

ISSUES CLOSED: #3519
```
[x] Bugfix
[ ] Feature
```
Issue Number: #3519 
add css break-word for long text displayed in the toast text box
```
[ ] Yes
[x] No
```

fix(stark-ui): add word-break to stark-toast

---

packages/stark-ui/src/modules/app-menu/components/app-menu-item.component.spec.ts
packages/stark-ui/src/modules/app-menu/components/app-menu-item.component.ts

```
[ ] Bugfix
[x] Feature
```
When navigate to a child state that is not in the menu, the menu is not highlighted any more.
Issue Number:  #3521 
Check if the current state is a child state of the menu element if the menu element do not have child menu
```
[ ] Yes
[X] No
```

feat(stark-ui): keep highlight the menu when go to child state

---

build.sh

Previously, a similar tgz filename with the last commit hash was generated for each build. Due to migration to npm v7, we encountered issues when installing new bundled stark packages. npm v7 automatically installed the previous cached version instead of installing new generated tgz file
```
[x] Bugfix
[ ] Feature
```
Previously, a similar tgz filename with the last commit hash was generated for each build. 
Due to migration to npm v7, we encountered issues when …

build(build-main): add a timestamp to the name of the packages that are generated locally

---

packages/stark-ui/src/modules/restrict-input-directive/directives/restrict-input.directive.ts

KeybordEvent.char is deprecated and will be remove from typesscript. To prepare the update to angular 13 we need to remveoved occureneces
ISSUES CLOSED: #3634
```
[x] Bugfix
[ ] Feature
```
Issue Number: #3634 
```
[ ] Yes
[x] No
```

fix(stark-ui): remove KeybordEvent.char

---

.github/workflows/build.yml

Remove old stark install scripts that are no longer valid.
```
[X] Bugfix
[ ] Feature
```
The release stage triggers the following removed scripts:
```bash
npm run install:ci:stark-build
npm run install:ci:stark-core
npm run install:ci:stark-rbac
npm run install:ci:stark-ui
```
The release stage has been adapted to no longer use these install scripts.
```
[ ] Yes
[X] No
```

ci(build-main): fix install of stark deps in release stage of the build workflow

---

gh-deploy.sh

```
[X] Bugfix
[ ] Feature
```
Git user configuration is not applied in the repository cloned in the gh-deploy.sh script.
No commit can be done by the script because of the missing user's git configuration.
The condition to define the user's git configuration has been moved in the cloned repository folder.
```
[ ] Yes
[X] No
```

ci(build-main): fix git user information in gh-deploy.sh script

---

packages/stark-core/src/modules/logging/services/logging.service.ts

ISSUES CLOSED: #3620
```
[x] Bugfix
[ ] Feature
```
Issue Number: #3620 
The correlation-id is now generated even when the loggingFlush is disabled.
```
[ ] Yes
[x] No
```

fix(stark-core): enable correlation-id generation when `loggingFlushDisabled == true`

---

packages/stark-core/src/modules/routing/services/routing.service.spec.ts
packages/stark-core/src/modules/routing/services/routing.service.ts

ISSUE CLOSED: #3766
```
[X] Bugfix
[ ] Feature
```
Issue Number: #3766 
Query params in URL are handled correctly.
```
[ ] Yes
[X] No
```

fix(stark-core): fix support for URL query parameters

---

.github/workflows/build.yml
.github/workflows/bump-angular-deps.yml
.github/workflows/dependabot-sync-stark-dependencies.yml

```
[ ] Bugfix
[ ] Feature
```
GH Workflow is using a deprecated action (upload-artifact@v2) which is deprecated.
More details on: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
The "main" NodeJS version is 18 but we use internally NodeJS 20 to build Stark. 
GH Actions in all workflows are up-to-date.
The main NodeJS version is now 20 and we execute tests on NodeJS 22 also. 
Finally, we now depend on the latest …

Feature/upgrade GitHub actions stark12

---

docs/MIGRATION_ANGULAR_16.md
docs/MIGRATION_GUIDE_STARK_12.md
packages/stark-testing/karma.conf.js

In test, we use `puppeteer` to setup chrome
ISSUES CLOSED: #4028
```
[x] Bugfix
[ ] Feature
```
Applications using stark-testing doesn't use chrome coming from `puppeteer`
Issue Number: #4028
Application using stark-testing use chrome coming from `puppeteer`
Documentation has been updated when using stark 12.0.0-alpha.x and 12.0.0-beta.x
```
[] Yes
[x] No
```

fix(stark-testing): make sure to use chrome from `puppeteer`
