.idea/vcs.xml
This file was accidently committed in the first commit. It's time to remove it :)
=> fix(build): Remove vcs.xml file

packages/stark-core/package.json
Just adapting package.json to follow Angular package format v5.0
=> [#73] adapt package.json

package.json, packages/rollup.config.js, packages/stark-build/config/stylelint.config.js, packages/stark-build/config/tslint.json, packages/stark-build/tsconfig.json, packages/stark-core/rollup.config.js, packages/tsconfig.json, starter/src/app/home/title/title.service.ts
```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
```
=> refactor(build): added missing rollup config

CONTRIBUTING.md, build-functions.sh, build.sh, package.json, packages/stark-build/config/webpack.common.js, packages/stark-build/config/webpack.dev.js, packages/stark-build/config/webpack.github-deploy.js, packages/stark-build/config/webpack.prod.js, packages/stark-build/config/webpack.test.js
```
[ ] Bugfix
[ ] Feature
```
uglify-es is the npm package based off of the harmony branch of uglify supporting ES2015+. 
With this PR we're aligned with what Angular does on its own repo.
I've also fixed a Webpack config issue for prettier (didn't pick up the correct config by default)
```
[ ] Yes
[x] No
```
=> refactor(build): improved main build

build-functions.sh, package.json, packages/tsconfig.json, starter/package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> Updated main build & starter's config

README.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> doc(readme): added thank you note for travis, jetbrains and browserstack

CONTRIBUTING.md
```
[ ] Bugfix
[ ] Feature
```
Added workflow explanation
```
[ ] Yes
[x] No
```
=> docs(workflow): explained the proposed workflow with git flow

packages/stark-core/src/logging/logging.module.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(logging): uncomment reducer implementation in logging.module.ts

.travis.yml, package.json, packages/rollup.config.common-data.js, packages/stark-core/rollup.config.js, packages/stark-testing/karma.conf.typescript.ci.js, packages/stark-testing/karma.conf.typescript.js, packages/stark-testing/package.json, packages/tsconfig.json, starter/package.json
Improvement of Rollup config
```
[X] Bugfix
[ ] Feature
```
Some imports were not correctly defined in Rollup, as uuid, moment, ... and broke the tests in the starter.
TsConfig adapted based on Angular one. Globals added rollup.config of Stark-Core and in the common one.
```
[ ] Yes
[X] No
```
=> fix(build) fix(testing) Adapt rollup for make it work with karma-ts. Declare needed globals in rollup config. Clean up karma.conf

packages/stark-core/package.json, packages/stark-testing/package.json, starter/package.json
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe:
```
Update dependencies for testing
```
[ ] Yes
[X] No
```
=> chore(testing) chore(core) Update dependencies for testing

packages/stark-core/package.json, packages/stark-core/src/logging/services/logging.service.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #258
Compilation error fixed.
```
[ ] Yes
[x] No
```
=> fix: Use latest rxjs forward-compat to solve ErrorObservable issues

docs/COMMON_DEV_ERRORS.md
Added a file COMMON_DEV_ERRORS.md in docs folder for keeping our fix for some errors we can see often with the build part or simply during the dev. Sometimes, those error messages are not really clear so I think it's important to reference them somewhere with an explanation.
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> doc(common-errors) Add md file with common errors and how to fix them

build.sh, packages/rollup.config.common-data.js
```
[X] Bugfix
[ ] Feature
```
Rollup complained about unresolved dependencies. Fixed them except tslib one.
```
[ ] Yes
[X] No
```
=> fix(build) Fix some unresolved dependencies in Rollup + Ignore coverage folder in build

packages/rollup.config.common-data.js, packages/stark-build/config/tslint.json, packages/stark-build/config/webpack.common.js, packages/stark-build/config/webpack.prod.js, packages/stark-core/src/common/routes/index.ts, packages/stark-core/src/common/routes/routes.ts, packages/stark-core/src/common/store/starkCoreApplicationState.ts, packages/stark-core/src/configuration/entities/application/app-config.entity.intf.ts, packages/stark-core/src/http/http.module.ts, packages/stark-core/src/http/services/http.service.spec.ts, packages/stark-core/src/http/services/http.service.ts, packages/stark-core/src/logging/actions/logging.actions.ts, packages/stark-core/src/logging/logging.module.ts, packages/stark-core/src/logging/services/logging.service.spec.ts, packages/stark-core/src/logging/services/logging.service.ts, packages/stark-core/src/logging/testing/logging.mock.ts, packages/stark-core/src/routing/actions/routing.actions.ts, packages/stark-core/src/routing/services/routing.service.spec.ts, packages/stark-core/src/session/actions/session.actions.ts, packages/stark-core/src/session/reducers/session.reducer.spec.ts, packages/stark-core/src/session/reducers/session.reducer.ts, packages/stark-core/src/session/services/session.service.spec.ts, packages/stark-core/src/session/services/session.service.ts, packages/stark-core/src/session/session.module.ts, packages/stark-core/src/test/unit-testing/unit-testing-utils.ts, packages/stark-core/src/user/entities/user-profile.entity.intf.ts, packages/stark-core/src/user/entities/user.entity.ts, packages/stark-core/src/util/validation-methods.util.ts, packages/stark-core/tsconfig.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[X] No
```
=> style(all) Apply Prettier on all files because of an issue with Prettier precommit hook

packages/stark-core/src/common/store/starkCoreApplicationState.ts, packages/stark-core/src/configuration/entities/index.ts, packages/stark-core/src/configuration/entities/metadata/application-metadata.entity.intf.ts, packages/stark-core/src/configuration/entities/mock-data/index.ts, packages/stark-core/src/configuration/entities/mock-data/mock-data.entity.intf.ts, packages/stark-core/src/http/repository/http-abstract-repository.spec.ts, packages/stark-core/src/http/services/http.service.spec.ts, packages/stark-core/src/logging/index.ts, packages/stark-core/src/logging/reducers/logging.reducer.spec.ts, packages/stark-core/src/session/index.ts, packages/stark-core/src/session/reducers/session.reducer.spec.ts, packages/stark-core/src/user/actions/index.ts, packages/stark-core/src/user/actions/user.actions.ts, packages/stark-core/src/user/index.ts, packages/stark-core/src/user/reducers/index.ts, packages/stark-core/src/user/reducers/user.reducer.spec.ts, packages/stark-core/src/user/reducers/user.reducer.ts, packages/stark-core/src/user/repository/index.ts, packages/stark-core/src/user/repository/user.repository.intf.ts, packages/stark-core/src/user/repository/user.repository.ts, packages/stark-core/src/user/services/index.ts, packages/stark-core/src/user/services/user.service.intf.ts, packages/stark-core/src/user/services/user.service.spec.ts, packages/stark-core/src/user/services/user.service.ts, packages/stark-core/src/user/user.module.ts
```
[ ] Bugfix
[x] Feature
```
Implement User module. Fix logging and session reducer tests
```
[ ] Yes
[x] No
```
=> feat(core) Implement User module. Fix logging and session reducer tests

.travis.yml, packages/stark-core/src/util/date.util.spec.ts, packages/stark-core/src/util/date.util.ts, packages/stark-core/src/util/index.ts
```
[ ] Bugfix
[x] Feature
```
Add date util and tests
Add TimeZone specification in travis.yml
```
[ ] Yes
[x] No
```
=> feat (core): Added date util

.travis.yml, README.md, package.json, packages/stark-core/karma.conf.typescript.ci.js, packages/stark-testing/karma.conf.typescript.ci.js, packages/stark-testing/package.json
```
[ ] Bugfix
[X] Feature
```
Coverage report is generated by `karma-typescript` on CI mode but is not loaded to any code coverage tool to see the reports.
Issue Number: #84 #273 
Code coverage is generated by `karma-coverage` by using the latest `istanbul` (1.x) and loaded by Travis to Coveralls to see the coverage report.
```
[ ] Yes
[X] No
```
=> feat(coverage): add support for code coverage with Coveralls

package.json, packages/stark-build/package.json
```
[ ] Bugfix
[ ] Feature
```
Build working correctly but its performance could be improved.
Issue Number: #76 
Improved performance in build due to [rollup](https://github.com/rollup/rollup/blob/master/CHANGELOG.md#0580) and [uglifyjs-webpack-plugin](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/blob/master/CHANGELOG.md#125-2018-04-18) upgrades
```
[ ] Yes
[X] No
```
=> chore(build-perf): upgrade dependencies aimed to improve build performance

packages/rollup.config.common-data.js
```
[X] Bugfix
[ ] Feature
```
Rollup shows a warning about `ibantools `being an unresolved dependency.
Rollup identifies corrctly `ibantools` as an external dependency.
```
[ ] Yes
[X] No
```
=> fix(rollup): add ibantools to external dependencies

build-functions.sh, packages/rollup.config.common-data.js
```
[X] Bugfix
[ ] Feature
```
Build process is too verbose.
Fixed issue with detecting warning type for rollup in build-functions.sh
Fixed also an unresolved dependency for @uirouter/angular in rollup.
```
[ ] Yes
[X] No
```
=> fix(build) Fix display of rollup warning messages + Add @uirouter/angular to external deps of rollup

build-functions.sh, packages/rollup.config.common-data.js
```
[X] Bugfix
[ ] Feature
```
Missing some warning messages.
Displaying warning message for circular dependencies.
```
[ ] Yes
[X] No
```
=> fix(build-main): add support for circular dependency warning. Fix rollup external dependencies

package.json, starter/package.json
```
[x] Bugfix
[ ] Feature
```
We still had 2 scripts using rimraf from global so I added npx for those ones.
```
[ ] Yes
[x] No
```
=> fix(stark-all): add npx  remaining script calling global rimraf package

CONTRIBUTING.md, README.md
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #338 
- rewrite Commit Message Guidelines in CONTRIBUTING.md to match Commitlint requirements
- add badges for Prettier and Commitizen in README.md
```
[ ] Yes
[x] No
```
=> docs(docs): Rewrite Commit Message Guidelines and add badges in README

.gitignore, starter/.gitignore
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe:
```
Added exclusions for vs code files
```
[ ] Yes
[x] No
```
=> chore(build): added exclusions for vs code

packages/stark-build/config/webpack.dev.js, starter/package.json
```
[x] Bugfix
[ ] Feature
```
- Fix bug in the starter when `reports` folder doesn't exist
- Add script to run webpack monitor (`npm run start:monitor`). In other situations, webpack monitor is not launched and HMR can work (Webpack monitor make crash the HMR). 
- Update  `webpack dev config` for the previous point
```
[ ] Yes
[x] No
```
=> fix(stark-build) fix(stark-starter): fix webpack monitor issues with reports folder and HMR

packages/stark-core/tsconfig-build.json, packages/stark-core/tsconfig.spec.json, packages/stark-ui/src/modules/app-logo/components/app-logo.component.html, packages/stark-ui/src/modules/app-logo/components/app-logo.component.ts, packages/stark-ui/tsconfig-build.json, packages/stark-ui/tsconfig.spec.json, starter/package.json
ISSUES CLOSED: #376
```
[ ] Bugfix
[X] Feature
```
Issue Number: #376 
Inlining template into stark-ui and stark-core
```
[ ] Yes
[X] No
```
=> feat(stark-all): enable resourcesInlining once we have Angular 6 for inlining template in components

docs/WEBPACK.md, packages/stark-build/config/webpack.common-data.js
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #148 
Docs describing the new feature.
```
[ ] Yes
[X] No
```
=> docs(stark-build): docs for base url and deploy url customization support

package.json, packages/stark-build/config/build-utils.js, packages/stark-build/config/webpack.common.js, packages/stark-build/config/webpack.prod.js, packages/stark-core/src/configuration/entities/application/app-config.entity.ts, packages/stark-core/src/configuration/entities/language/language.entity.ts, packages/stark-core/src/modules/http/services/http.service.ts, packages/stark-core/src/modules/settings/effects/settings.effects.spec.ts, packages/stark-ui/package.json, packages/stark-ui/src/modules/app-logo/components/app-logo.component.ts, packages/stark-ui/tslint.json
```
[X] Bugfix
[ ] Feature
```
- Some FIXME's are now obsolete due to issues with old Angular compiler version (they are no longer happening after NG6 upgrade).
- Some files not formatted correctly.
- stark-ui package not included in the `lint:all` script
- missing presets in stark-ui `tslint.json` file
All the issues mentioned are fixed.
```
[ ] Yes
[X] No
```
=> fix(stark-all): fix some imports to remove obsolete FIXME's. Format code with Prettier. Fix stark-ui linting.

packages/stark-build/config/webpack.common.js, packages/stark-build/config/webpack.dev.js, packages/stark-build/config/webpack.prod.js
ISSUES CLOSED: #401
```
[X] Bugfix
[ ] Feature
```
Issue Number: #401 
Sourcemaps are working again 😃
```
[ ] Yes
[X] No
```
=> fix(build): fix sourcemaps in PROD and in DEV

showcase/src/app/app.component.ts, showcase/src/app/app.e2e.ts, showcase/src/app/home/home.e2e.ts, showcase/src/environments/environment.e2e.prod.ts, showcase/src/environments/environment.hmr.ts, showcase/src/environments/environment.prod.ts, showcase/src/environments/environment.ts, showcase/src/main.browser.ts, starter/config/webpack-custom-config.dev.json, starter/src/app/app.component.ts, starter/src/app/app.e2e.ts, starter/src/app/home/home.e2e.ts, starter/src/environments/environment.e2e.prod.ts, starter/src/environments/environment.hmr.ts, starter/src/environments/environment.prod.ts, starter/src/environments/environment.ts, starter/src/main.browser.ts
```
[ ] Bugfix
[ ] Feature
```
TSLint checks completely disabled in some files which cause some TSLint violations to be hidden.
Only specific rules disabled when needed instead of disabling all rules. Wrong formatting in all files is fixed by prettier.
```
[ ] Yes
[X] No
```
=> style(stark-all): remove obselete/invalid tslint:disable flags. Run prettier to fix wrong formatting

starter/README.md
ISSUES CLOSED: #32
```
[ ] Bugfix
[ ] Feature
```
The application structure is not documented
Issue Number: #32 
The application structure is documented
```
[ ] Yes
[x] No
```
=> docs(stark-starter): add documentation for the application structure in the ReadMe file

release-publish.sh
ISSUES CLOSED: #357
```
[X] Bugfix
[ ] Feature
```
Issue Number: #357 
Nightly build works again  
```
[ ] Yes
[X] No
```
=> fix(stark-all): fix nightly build release on Travis

packages/stark-core/src/modules/routing/services/routing.service.ts
ISSUES CLOSED: #389
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #389 
Alll tslint rule flags are correctly defined to disable just the necessary rules if needed.
```
[ ] Yes
[X] No
```
=> style(stark-core): fix minor issues with tslint rule flags

docs/WEBPACK.md, packages/stark-build/config/webpack.common.js, packages/stark-build/package.json, showcase/config/index-head-config.js, showcase/package.json, showcase/src/index.html, starter/config/index-head-config.js, starter/package.json, starter/src/index.html
```
[ ] Bugfix
[x] Feature
```
Currently, the index.html header contains all our <link> and <meta> tags. Another way of implementing that header is described here: 
https://github.com/gdi2290/angular-starter/blob/master/config/head-config.common.js
https://github.com/gdi2290/angular-starter/blob/master/config/html-elements-plugin/index.js
Issue Number: #60 
The links above have been followed and the same way of implementing the head of index.html as been used. 
```
[ ] …
```
=> feat(stark-starter):  review index.html head section and implement webpack html elements plugin

docs/TSCONFIG.md
Closes: #364 
```
[ ] Bugfix
[ ] Feature
```
The structure of the tsconfig files in the project was not documented. 
The structure is now documented
```
[ ] Yes
[x] No
```
=> docs(docs): add documentation about tsconfig files structure

showcase/angular.json
```
[X] Bugfix
[ ] Feature
```
The baseHref was removed from the `angular.json` file of the showcase due to PRs #471 and #477. However the showcase is broken since Angular requires a baseHref to be defined.
Showcase correctly running since the baseHref is defined in the `angular.json` file.
```
[ ] Yes
[X] No
```
=> fix(stark-demo): fix baseHref in angular.json file

showcase/src/app/demo/demo.component.spec.ts, showcase/src/app/demo/demo.component.ts, showcase/src/app/shared/example-viewer/example-viewer.component.spec.ts, showcase/src/app/shared/example-viewer/example-viewer.component.ts
ISSUES CLOSED: #484
```
[ ] Bugfix
[x] Feature
```
The logging service is not present in the ExampleViewer component 
Issue Number: #484 
The LoggingService is added to the ExampleViewer component  and in the unit tests
```
[ ] Yes
[x] No
```
=> fix(stark-demo): add StarkLoggingService to the ExampleViewer tests

packages/stark-ui/package.json, packages/stark-ui/src/modules.ts, packages/stark-ui/src/modules/slider.ts, packages/stark-ui/src/modules/slider/components.ts, packages/stark-ui/src/modules/slider/components/_slider-theme.scss, packages/stark-ui/src/modules/slider/components/slider-config.intf.ts, packages/stark-ui/src/modules/slider/components/slider-pips.intf.ts, packages/stark-ui/src/modules/slider/components/slider.component.html, packages/stark-ui/src/modules/slider/components/slider.component.spec.ts, packages/stark-ui/src/modules/slider/components/slider.component.ts, packages/stark-ui/src/modules/slider/slider.module.ts, packages/stark-ui/src/stark-ui.ts, packages/stark-ui/src/util.ts, packages/stark-ui/src/util/dom.util.spec.ts, packages/stark-ui/src/util/dom.util.ts, showcase/src/app/app.module.ts, showcase/src/styles/_theme.scss
```
[ ] Bugfix
[x] Feature
```
The slider component is not yet added to the stark-ui package.
Issue Number: #448 
The slider component is added to the stark-ui package
```
[ ] Yes
[x] No
```
The slider is not yet integrated in the Showcase.
=> feat(stark-ui): implement the Stark-Slider component

packages/stark-core/src/common/bootstrap/abstract-stark-main.ts
ISSUES CLOSED: #506
```
[X] Bugfix
[ ] Feature
```
Issue Number: #506 
Angular prod mode correctly enabled in production builds.
```
[ ] Yes
[X] No
```
=> fix(stark-core): refactor AbstractStarkMain to enable Angular prod mode before bootstraping the app in production build

showcase/src/app/shared/example-viewer/_example-viewer-theme.scss, showcase/src/app/shared/example-viewer/example-viewer.component.html
ISSUES CLOSED: #515
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Style improvement
```
Issue Number: #515 
- Remove the border radius from the pretty print inside of the exemple viewer
- Add the same background than the pretty print to the example viewer container for smoother transition
=> feat(stark-demo): improve example viewer styling

packages/stark-core/src/common/translations/translations/en.ts, packages/stark-core/src/common/translations/translations/fr.ts, packages/stark-core/src/common/translations/translations/nl.ts, packages/stark-ui/src/modules/action-bar/components/action-bar.component.html, packages/stark-ui/src/modules/table/components/column.component.html, packages/stark-ui/src/modules/table/components/dialogs/multisort.component.html, packages/stark-ui/src/modules/table/components/table.component.html, packages/stark-ui/src/modules/table/components/table.component.spec.ts, packages/stark-ui/src/modules/table/table.module.ts
ISSUES CLOSED: #502
```
[x] Bugfix
[ ] Feature
```
Issue Number: #502 
- Translation of stark-table
- Translation of stark-action-bar
```
[ ] Yes
[x] No
```
=> fix(stark-ui): tooltip translation + table translation

packages/stark-core/package.json
```
[ ] Bugfix
[ ] Feature
```
Stark-core uses an [old version of `ng-idle`](https://github.com/HackedByChinese/ng2-idle/blob/master/CHANGELOG.md#200-beta15-2018-03-29) packages which is meant to be used with Angular 5 and below, which means that it uses an old version of `rxjs` library as well.
The [latest version of ng-idle](https://github.com/HackedByChinese/ng2-idle/blob/master/CHANGELOG.md#600-beta3-2018-07-16) which is compatible with Angular 6 is used in …
=> chore(stark-core): update ng-idle packages to the latest version

packages/stark-ui/src/modules.ts, packages/stark-ui/src/modules/keyboard-directives.ts, packages/stark-ui/src/modules/keyboard-directives/directives.ts, packages/stark-ui/src/modules/keyboard-directives/directives/on-enter-key.directive.spec.ts, packages/stark-ui/src/modules/keyboard-directives/directives/on-enter-key.directive.ts, packages/stark-ui/src/modules/keyboard-directives/keyboard-directives.module.ts, showcase/src/app/app.component.html, showcase/src/app/app.routes.ts, showcase/src/app/demo/demo.module.ts, showcase/src/app/demo/index.ts, showcase/src/app/demo/keyboard-directives/index.ts, showcase/src/app/demo/keyboard-directives/keyboard-directives.component.html, showcase/src/app/demo/keyboard-directives/keyboard-directives.component.scss, showcase/src/app/demo/keyboard-directives/keyboard-directives.component.ts, showcase/src/assets/examples/keyboard-directives/on-enter-key-directive.html, showcase/src/assets/examples/keyboard-directives/on-enter-key-directive.ts, showcase/src/assets/translations/en.json, showcase/src/assets/translations/fr.json, showcase/src/assets/translations/nl.json
ISSUES CLOSED: #538 #548
```
[ ] Bugfix
[X] Feature
```
Issue Number: #538 #548 
OnEnterKey directive and module implemented
```
[ ] Yes
[X] No
```
=> feat(stark-ui): implement OnEnterKey directive and module

README.md
```
[ ] Bugfix
[ ] Feature
```
I'm not part of the authors list 😢 
I am part of the authors list 😄 
```
[X] Yes  <= professionally
[ ] No
```
=> docs(docs): add me as author :)

packages/stark-ui/src/modules/app-logo/components/app-logo.component.spec.ts, packages/stark-ui/src/modules/keyboard-directives/directives.ts, packages/stark-ui/src/modules/keyboard-directives/directives/restrict-input.directive.spec.ts, packages/stark-ui/src/modules/keyboard-directives/directives/restrict-input.directive.ts, packages/stark-ui/src/modules/keyboard-directives/keyboard-directives.module.ts, packages/stark-ui/src/modules/slider/components/slider.component.spec.ts, packages/stark-ui/src/modules/svg-view-box/directives/svg-view-box.directive.spec.ts, packages/stark-ui/src/modules/svg-view-box/directives/svg-view-box.directive.ts, showcase/src/app/demo/keyboard-directives/keyboard-directives.component.html, showcase/src/app/demo/keyboard-directives/keyboard-directives.component.scss, showcase/src/assets/examples/keyboard-directives/restrict-input-directive.html, showcase/src/assets/examples/keyboard-directives/restrict-input-directive.ts, showcase/src/assets/translations/en.json, showcase/src/assets/translations/fr.json, showcase/src/assets/translations/nl.json
ISSUES CLOSED: #546 #550 
```
[ ] Bugfix
[X] Feature
```
Issue Number: #546 #550 
RestrictInput directive and module implemented
```
[ ] Yes
[X] No
```
=> feat(stark-ui): implement RestrictInput directive and module

showcase/src/assets/translations/en.json, showcase/src/assets/translations/fr.json, showcase/src/assets/translations/nl.json
```
[X] Bugfix
[ ] Feature
```
Translations in the pretty-print demo are not displayed correctly
Issue Number: #560 
Translations are now displayed correctly
```
[ ] Yes
[X] No
```
=> fix(stark-demo): fix pretty-print demo translations

.travis.yml
Fix greenkeeper updates by adapting .travis.yml file
```
[X] Bugfix
[ ] Feature
```
Greenkeeper should work correctly
```
[ ] Yes
[X] No
```
=> fix(build-main): fix greenkeeper branch checks in .travis.yml file for package-lock updating

.travis.yml, gh-deploy.sh, release-publish.sh, scripts/ci/_travis-fold.sh
ISSUES CLOSED: #605
```
[X] Bugfix
[ ] Feature
```
We assign a custom value to `TRAVIS` variable (1)
Issue Number: #605
We use `TRAVIS` variable as it is by default.
```
[ ] Yes
[X] No
```
=> fix(build-main): remove custom value for TRAVIS variable

.travis.yml
```
[X] Bugfix
[ ] Feature
```
Greenkeeper-lockfile is failing
Greenkeeper-lockfile is working
```
[ ] Yes
[X] No
```
=> fix(greenkeeper): fix greenkeeper-lockfile

package-lock.json
```
[X] Bugfix
[ ] Feature
```
Travis build failing because of bad package-lock.json
Travis build works
```
[ ] Yes
[X] No
```
=> fix(greenkeeper) update package-lock.json manually

.travis.yml, package-lock.json, packages/stark-build/package-lock.json, packages/stark-core/package-lock.json, packages/stark-testing/package-lock.json, packages/stark-ui/package-lock.json, showcase/package-lock.json, showcase/package.json, starter/package-lock.json, starter/package.json
```
[ ] Bugfix
[X] Feature
```
usage of npm 5.8.0
usage of npm 6.3.0
```
[X] Yes
[ ] No
```
=> feat(build-main): use npm 6.3.0 + adapt package-lock.json files

packages/stark-ui/src/modules.ts, packages/stark-ui/src/modules/app-logout.ts, packages/stark-ui/src/modules/app-logout/app-logout.module.ts, packages/stark-ui/src/modules/app-logout/components.ts, packages/stark-ui/src/modules/app-logout/components/app-logout.component.html, packages/stark-ui/src/modules/app-logout/components/app-logout.component.spec.ts, packages/stark-ui/src/modules/app-logout/components/app-logout.component.ts, showcase/src/app/app.component.html, showcase/src/app/app.module.ts, showcase/src/app/app.routes.ts, showcase/src/app/demo/demo.module.ts, showcase/src/app/demo/header/header.component.ts, showcase/src/app/demo/index.ts, showcase/src/app/demo/logout/index.ts, showcase/src/app/demo/logout/logout.component.html, showcase/src/app/demo/logout/logout.component.ts, showcase/src/assets/examples/logout/logout-default.html, showcase/src/assets/examples/logout/logout-logout.html, showcase/src/assets/translations/en.json, showcase/src/assets/translations/fr.json, showcase/src/assets/translations/nl.json
ISSUES CLOSED: #588
```
[ ] Bugfix
[x] Feature
```
No logout components were available.
Issue Number: #588
A logout component is now available.
```
[ ] Yes
[x] No
```
=> feat(stark-ui): implement the logout component/module

packages/stark-core/package-lock.json, packages/stark-core/package.json, packages/stark-ui/tsconfig-build.json
```
[x] Bugfix
[ ] Feature
```
The lodash dependency was not implemented in the package.json
Issue Number: #630 
The lodash dependency is imported in package.json of stark-core
```
[ ] Yes
[x] No
```
=> fix(stark-core): added lodash dependency in package.json

packages/stark-ui/src/modules/breadcrumb/components/breadcrumb.component.spec.ts, packages/stark-ui/src/modules/breadcrumb/components/breadcrumb.component.ts
```
[x] Bugfix
[ ] Feature
```
TranslateService was wrongly importated in the breadcrumb.component.ts file
Issue Number: #633
The service has been removed. 
```
[ ] Yes
[ ] No
```
=> fix(stark-ui): removed TranslateService from breadcrumb component

packages/stark-ui/assets/themes/_button-theme.scss
ISSUES CLOSED: #619
```
[x] Bugfix
[ ] Feature
```
Issue Number: #619 
Icon is now aligned vertically in the different buttons
```
[ ] Yes
[x] No
```
=> fix(stark-ui): button - align icon vertically

packages/stark-ui/src/modules/slider/components/slider.component.html, showcase/src/app/app.component.html, showcase/src/app/app.module.ts, showcase/src/app/app.routes.ts, showcase/src/app/demo/demo.module.ts, showcase/src/app/demo/index.ts, showcase/src/app/demo/slider/index.ts, showcase/src/app/demo/slider/slider.component.html, showcase/src/app/demo/slider/slider.component.scss, showcase/src/app/demo/slider/slider.component.ts, showcase/src/assets/examples/slider/horizontal-range-slider.html, showcase/src/assets/examples/slider/horizontal-range-slider.scss, showcase/src/assets/examples/slider/horizontal-range-slider.ts, showcase/src/assets/examples/slider/simple-horizontal-slider.html, showcase/src/assets/examples/slider/simple-horizontal-slider.scss, showcase/src/assets/examples/slider/simple-horizontal-slider.ts, showcase/src/assets/examples/slider/simple-vertical-slider.html, showcase/src/assets/examples/slider/simple-vertical-slider.scss, showcase/src/assets/examples/slider/simple-vertical-slider.ts, showcase/src/assets/examples/slider/vertical-range-slider.html, showcase/src/assets/examples/slider/vertical-range-slider.scss, showcase/src/assets/examples/slider/vertical-range-slider.ts, showcase/src/assets/translations/en.json, showcase/src/assets/translations/fr.json, showcase/src/assets/translations/nl.json
ISSUES CLOSED: #561
```
[ ] Bugfix
[x] Feature
```
Issue Number: #561
A new demo page is added to demonstrate the use of the slider component.
```
[ ] Yes
[x] No
```
=> feat(stark-demo): add Slider component to the Showcase Demo

package-lock.json, package.json
Closes #643
```
[ ] Bugfix
[ ] Feature
```
Current version: 7.0.1
Updated to the latest version: 7.1.1
```
[ ] Yes
[X] No
```
=> chore(package): update @commitlint/config-conventional to version 7.1.1

package-lock.json, package.json
Closes #644
```
[ ] Bugfix
[ ] Feature
```
Current version: 7.0.0
Updated to the latest version: 7.1.1
```
[ ] Yes
[X] No
```
=> chore(package): update @commitlint/cli to version 7.1.1

package-lock.json, package.json
Closes #627
```
[ ] Bugfix
[ ] Feature
```
Current version: 7.5.0
Updated to the latest version: 7.6.0
```
[ ] Yes
[X] No
```
=> chore(package): update release-it to version 7.6.0

package-lock.json, package.json
Closes #656
```
[ ] Bugfix
[ ] Feature
```
Current version: 0.65.0
Updated to the latest version: 0.65.2
```
[ ] Yes
[X] No
```
=> chore(package): update rollup to version 0.65.2

packages/stark-core/src/modules/session/services/session.service.ts, packages/stark-core/src/modules/settings/effects/settings.effects.ts, showcase/src/app/app.module.ts
ISSUES CLOSED: #578
```
[ ] Bugfix
[x] Feature
```
The default language is always "nl"
Issue Number: #578 
The browser language is used as the default language.
```
[ ] Yes
[x] No
```
=> feat(stark-core): use the browser language as the default language

packages/stark-ui/src/modules/svg-view-box/directives/svg-view-box.directive.ts
```
[ ] Bugfix
[ ] Feature
```
Examples in JSDoc is not aligned with what is supported by [Compodoc](https://compodoc.app/guides/jsdoc-tags.html).
JSDoc is fixed to take advantage of the code example view supported by [Compodoc](https://compodoc.app/guides/jsdoc-tags.html)
```
[ ] Yes
[X] No
```
=> docs(stark-ui): fix SvgViewBox directive JSDoc for better readability

showcase/src/app/app.component.html
```
[X] Bugfix
[ ] Feature
```
AppLogo component is no longer in the header. It was acciddentaly removed in #638 
AppLogo is added back in the header
```
[ ] Yes
[X] No
```
=> fix(stark-demo): add AppLogo back in the header after being accidentally removed

package.json, packages/stark-ui/assets/styles/_variables.scss, packages/stark-ui/src/modules/dropdown/components/_dropdown-theme.scss, packages/stark-ui/src/modules/dropdown/components/_dropdown.component.scss, packages/stark-ui/src/modules/dropdown/components/dropdown.component.ts, packages/stark-ui/tslint.json, showcase/src/app/app.component.html, showcase/src/app/app.routes.ts, showcase/src/app/demo/demo.module.ts, showcase/src/app/demo/dropdown/demo-dropdown.component.html, showcase/src/app/demo/dropdown/demo-dropdown.component.scss, showcase/src/app/demo/dropdown/demo-dropdown.component.ts, showcase/src/app/demo/dropdown/index.ts, showcase/src/assets/examples/dropdown/white.css, showcase/src/assets/examples/dropdown/white.html, showcase/src/assets/examples/dropdown/white.ts, showcase/src/assets/translations/en.json, showcase/src/assets/translations/fr.json, showcase/src/assets/translations/nl.json, showcase/src/styles/_stark-styles.scss
ISSUES CLOSED: #642, #640
```
[ ] Bugfix
[x] Feature
```
New themes to display the dropdown in white as been added as well as a theme to display it in full width mode.
Issue Number: #642, #640
```
[ ] Yes
[x] No
```
=> feat(stark-ui): added white theme and full width for dropdown component

showcase/src/assets/css/.gitkeep
ISSUES CLOSED: #432
```
[ ] Bugfix
[ ] Feature
```
There was still a css sub-folder located in the assets folder.
Issue Number: #432 
The css sub-folder is removed from the assets folder.
```
[ ] Yes
[x] No
```
=> refactor(stark-demo): showcase application structure fix

starter/src/assets/css/.gitkeep
ISSUES CLOSED: #431
```
[ ] Bugfix
[ ] Feature
```
There was still a css sub-folder located in the assets folder.
Issue Number: #431
The css sub-folder is removed from the assets folder.
```
[ ] Yes
[x] No
```
=> refactor(stark-starter): starter application structure fix

packages/stark-ui/assets/styles/_base.scss, packages/stark-ui/assets/styles/_header.scss, packages/stark-ui/assets/styles/_typography.scss, packages/stark-ui/assets/styles/_variables.scss, packages/stark-ui/src/modules/pretty-print/components/_pretty-print.component.scss, showcase/src/app/app.component.html, showcase/src/app/app.routes.ts, showcase/src/app/demo/demo.module.ts, showcase/src/app/demo/index.ts, showcase/src/app/demo/typography/demo-typography.component.html, showcase/src/app/demo/typography/demo-typography.component.ts, showcase/src/app/demo/typography/index.ts, showcase/src/app/shared/example-viewer/_example-viewer-theme.scss, showcase/src/app/shared/example-viewer/example-viewer.component.html, showcase/src/app/shared/example-viewer/example-viewer.component.scss, showcase/src/app/shared/example-viewer/example-viewer.component.spec.ts, showcase/src/assets/examples/typography/mat.html, showcase/src/assets/examples/typography/stark.html, showcase/src/assets/translations/en.json, showcase/src/assets/translations/fr.json, showcase/src/assets/translations/nl.json
ISSUES CLOSED: #475, #671
```
[ ] Bugfix
[x] Feature
```
Issue Number: #475, #671
- Typography: h1, h2, h3, h4 matching with Material font map. I also changed the pretty-print font to use the same as the rest.
- Spaces: a `<section>` tag helps to organize the layout structure.
Check out the typography page, if we agree on this layout, I will then integrate it on the other pages.
```
[ ] Yes
[x] No
```
=> feat(stark-ui): typography + Spaces

greenkeeper.json, packages/rollup.config.common-data.js, packages/stark-ui/assets/styles/_variables.scss, packages/stark-ui/src/modules.ts, packages/stark-ui/src/modules/collapsible.ts, packages/stark-ui/src/modules/collapsible/collapsible.module.ts, packages/stark-ui/src/modules/collapsible/components.ts, packages/stark-ui/src/modules/collapsible/components/_collapsible-theme.scss, packages/stark-ui/src/modules/collapsible/components/_collapsible.component.scss, packages/stark-ui/src/modules/collapsible/components/collapsible.component.html, packages/stark-ui/src/modules/collapsible/components/collapsible.component.spec.ts, packages/stark-ui/src/modules/collapsible/components/collapsible.component.ts, showcase/src/app/app.component.html, showcase/src/app/app.routes.ts, showcase/src/app/demo/collapsible/demo-collapsible.component.html, showcase/src/app/demo/collapsible/demo-collapsible.component.scss, showcase/src/app/demo/collapsible/demo-collapsible.component.ts, showcase/src/app/demo/collapsible/index.ts, showcase/src/app/demo/demo.module.ts, showcase/src/app/demo/index.ts, showcase/src/assets/examples/collapsible/collapsible-custom.css, showcase/src/assets/examples/collapsible/collapsible-custom.html, showcase/src/assets/examples/collapsible/collapsible-custom.ts, showcase/src/assets/examples/collapsible/collapsible-default.css, showcase/src/assets/examples/collapsible/collapsible-default.html, showcase/src/assets/examples/collapsible/collapsible-default.ts, showcase/src/assets/translations/en.json, showcase/src/assets/translations/fr.json, showcase/src/assets/translations/nl.json, showcase/src/styles/_stark-styles.scss
```
[ ] Bugfix
[x] Feature
```
No collapsible component available.
Issue Number: #595 
Collapsible component is available
```
[ ] Yes
[x] No
```
=> feat(stark-ui): implement collapsible feature

packages/stark-ui/assets/styles/_colors.scss, packages/stark-ui/assets/styles/_variables.scss, packages/stark-ui/assets/themes/_button-theme.scss, packages/stark-ui/assets/themes/_card-theme.scss, packages/stark-ui/src/modules/action-bar/components/_action-bar-theme.scss, packages/stark-ui/src/modules/collapsible/components/_collapsible-theme.scss, packages/stark-ui/src/modules/dropdown/components/_dropdown-theme.scss, showcase/src/app/demo/card/demo-card.component.html, showcase/src/app/demo/card/demo-card.component.scss, showcase/src/app/demo/card/demo-card.component.ts, showcase/src/app/demo/colors/demo-colors.component.html, showcase/src/app/demo/colors/demo-colors.component.ts, showcase/src/app/shared/example-viewer/_example-viewer-theme.scss, showcase/src/app/shared/example-viewer/example-viewer.component.html, showcase/src/assets/translations/en.json, showcase/src/assets/translations/fr.json, showcase/src/assets/translations/nl.json, showcase/src/styles/_variables.scss
ISSUES CLOSED: #691
```
[ ] Bugfix
[x] Feature
```
Issue Number: #691
We use only palettes now to deal with theming
=> style(stark-ui): use palette colors for every stark colors

packages/stark-ui/assets/styles/_base.scss, showcase/src/app/app.component.css, showcase/src/app/app.component.html, showcase/src/app/app.component.ts, showcase/src/app/translation.config.ts
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #598 
Default language is now English.
The home button now redirects to the homepage.
Other small refactorings.
```
[ ] Yes
[X] No
```
=> feat(showcase): improve showcase and move styles from showcase to stark-ui

packages/stark-core/src/modules/http/entities/error/http-error-base.entity.intf.ts, packages/stark-core/src/modules/http/entities/error/http-error-base.entity.ts, packages/stark-core/src/modules/logging/entities/log-message.entity.intf.ts, packages/stark-core/src/modules/logging/services/logging.service.intf.ts, packages/stark-core/src/modules/logging/services/logging.service.spec.ts, packages/stark-ui/src/modules/collapsible/components/collapsible.component.spec.ts, packages/stark-ui/src/modules/toast-notification/components/toast-message.intf.ts, packages/stark-ui/src/modules/toast-notification/components/toast-notification.component.spec.ts, packages/stark-ui/src/modules/toast-notification/components/toast-notification.component.ts, packages/stark-ui/src/modules/toast-notification/services/toast-notification.service.intf.ts, packages/stark-ui/src/modules/toast-notification/services/toast-notification.service.spec.ts, packages/stark-ui/src/modules/toast-notification/services/toast-notification.service.ts
ISSUES CLOSED: #712
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #712 
No "circular dependencies" warning from Webpack
```
[ ] Yes
[X] No
```
=> chore(stark-all): refine some imports to avoid "circular dependencies" warning from Webpack

packages/stark-core/src/modules/xsrf/services/xsrf.service.spec.ts
```
[X] Bugfix
[ ] Feature
```
The XSRF unit tests fail randomly on Travis. This is due to an observable not correctly initialized.
All unit tests passing.
```
[ ] Yes
[X] No
```
=> fix(stark-core): fix failing XSRF service test

build-functions.sh, packages/rollup.config.common-data.js, packages/rollup.config.js, showcase/src/app/app.e2e.ts, showcase/src/app/shared/reference-block/reference-block.component.spec.ts, showcase/tslint.json, starter/src/app/app.e2e.ts
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #585 
- The build will fail if there are "unresolved dependencies" or "missing global variable name" errors from Rollup.
- `tslib` will always be resolved so it won't be an "unresolved dependency" in Rollup anymore.
- Removed console logs in unit tests
- Disable `no-identical-functions` ts lint rule in `app.e2e.ts` in Starter and Showcase due to a bug in such rule.
```
[ ] Yes
[X] No
```
=> chore(build): refactor build.sh to fail when Rollup detects "unresolved dependencies" or "missing global variable name".

packages/stark-ui/assets/styles/_base.scss, packages/stark-ui/assets/styles/_header.scss, packages/stark-ui/assets/styles/_typography.scss, packages/stark-ui/assets/styles/_variables.scss, packages/stark-ui/src/modules/app-sidebar/components/_app-sidebar.component.scss, showcase/src/app/app.component.html, showcase/src/app/app.component.ts, showcase/src/app/demo/table/demo-table.component.html, starter/src/app/app.component.html, starter/src/app/app.component.scss, starter/src/app/app.component.ts, starter/src/app/app.module.ts, starter/src/styles/_stark-styles.scss, starter/src/styles/_theme.scss, starter/src/styles/_variables.scss, starter/src/styles/styles.scss
ISSUES CLOSED: #696, #715, #723
```
[X] Bugfix
[ ] Feature
```
Issue Number: #696 #715 #723
- Footer: is now covered by the backdrop; I had to add a `min-height: 670px` on the `stark-main-container` as they do in Angular Material website. If there is enough content, that won't be a problem.
- Header is now correctly aligned in small devices
- Table has the correct font-size
```
[ ] Yes
[X] No
```
=> fix(stark-ui): style fix: footer, header and table. Adapt Showcase and Starter.

package-lock.json, package.json
Closes #742 
```
[ ] Bugfix
[ ] Feature
```
Current version: 0.66.2
Updated to the latest version: 0.66.4
```
[ ] Yes
[X] No
```
=> Greenkeeper/rollup 0.66.4

package-lock.json, package.json
Closes #737
```
[ ] Bugfix
[ ] Feature
```
Current version: 2.10.1
Updated to the latest version: 3.0.2
```
[ ] Yes
[X] No
```
=> Greenkeeper/commitizen 3.0.2

docs/ERROR_HANDLING.md, packages/stark-core/src/common/store/stark-core-application-state.ts, packages/stark-core/src/modules.ts, packages/stark-core/src/modules/error-handling.ts, packages/stark-core/src/modules/error-handling/actions.ts, packages/stark-core/src/modules/error-handling/actions/error-handling.actions.ts, packages/stark-core/src/modules/error-handling/error-handling.module.ts, packages/stark-core/src/modules/error-handling/handlers.ts, packages/stark-core/src/modules/error-handling/handlers/error-handler.ts, packages/stark-core/src/modules/routing/services/routing.service.spec.ts, packages/stark-core/src/modules/routing/services/routing.service.ts, packages/stark-core/src/modules/settings/settings.module.ts, showcase/src/app/app.module.ts, showcase/src/app/shared/effects/stark-error-handling.effects.ts, showcase/src/stark-app-config.json, starter/src/app/app.module.ts
ISSUES CLOSED: #116 
```
[ ] Bugfix
[x] Feature
```
Angular's ErrorHandler was used by default.
Issue Number: #116 #233 
We've created a new custom ErrorHandler that developers CAN use (they are not obliged to). 
```
[ ] Yes
[x] No
```
=> feat(stark-core): implementation of a custom error handler

showcase/src/styles/basscss-missing-variables.pcss, showcase/src/styles/styles.scss
```
[X] Bugfix
[ ] Feature
```
Issue Number: basscss/basscss#257
Temporarily add the missing PCSS variables in a separate file and load it before `basscss`.
```
[ ] Yes
[X] No
```
=> chore(stark-demo): temporary fix for the missing PCSS variables from basscss

showcase/package-lock.json, showcase/package.json, starter/package-lock.json, starter/package.json
Closes #791 
```
[ ] Bugfix
[ ] Feature
```
Current version: 1.0.0
Updated to the latest version: 1.0.3
```
[ ] Yes
[X] No
```
=> Greenkeeper/default/event-source-polyfill 1.0.3

showcase/config/json-server/data.json, showcase/karma.conf.ci.js, showcase/karma.conf.js, showcase/package-lock.json, showcase/package.json, showcase/src/app/app.module.ts, showcase/src/app/home/home.component.html, showcase/src/app/home/home.component.ts, showcase/src/app/in-memory-data/in-memory-data.module.ts, showcase/src/app/in-memory-data/index.ts, showcase/src/app/in-memory-data/interceptors/in-memory-data.interceptor.ts, showcase/src/app/in-memory-data/interceptors/index.ts, showcase/src/app/in-memory-data/services/in-memory-data.service.ts, showcase/src/app/in-memory-data/services/index.ts, showcase/src/stark-app-config.json, starter/package-lock.json
ISSUES CLOSED: #740 
```
[ ] Bugfix
[X] Feature
```
Issue Number: #75 #740
- Now the Preloading page is displayed instead of the Login page in the Showcase.
- The backend is mocked with an "in-memory" backend thanks to the [angular-in-memory-web-api](https://github.com/angular/in-memory-web-api) library.
```
[ ] Yes
[X] No
```
Re-created the `package-lock.json` files in Showcase and Starter.
=> feat(stark-demo): integrate "angular-in-memory-web-api" to mock backend

package-lock.json, package.json
Closes #820 
```
[ ] Bugfix
[ ] Feature
```
Current version: 2.0.5
Updated to the latest version: 2.0.11
```
[ ] Yes
[X] No
```
=> Greenkeeper/conventional changelog cli 2.0.11

package-lock.json
```
[ ] Bugfix
[ ] Feature
```
Potential [security vulnerability in "merge" library](https://nvd.nist.gov/vuln/detail/CVE-2018-16469).
The `package-lock.json` file has been re-generated since a [new version of the "merge" library has been released](https://www.npmjs.com/package/merge/v/1.2.1).
```
[ ] Yes
[X] No
```
=> chore(build-main): bump "merge" version to solve potential security vulnerability

packages/stark-ui/assets/styles/_media-queries.scss, packages/stark-ui/assets/styles/_old-variables.scss, showcase/src/app/app.component.ts, showcase/src/app/app.module.ts, showcase/src/app/app.routes.ts, showcase/src/app/getting-started/getting-started-component/_getting-started-theme.scss, showcase/src/app/getting-started/getting-started-component/_getting-started.component.scss, showcase/src/app/getting-started/getting-started-component/getting-started.component.html, showcase/src/app/getting-started/getting-started-component/getting-started.component.ts, showcase/src/app/getting-started/getting-started-component/index.ts, showcase/src/app/getting-started/getting-started-component/starter-structure.ts, showcase/src/app/getting-started/getting-started.module.ts, showcase/src/app/getting-started/index.ts, showcase/src/app/shared/example-viewer/_example-viewer-theme.scss, showcase/src/app/shared/index.ts, showcase/src/app/shared/shared.module.ts, showcase/src/app/shared/table-of-contents/_table-of-contents-theme.scss, showcase/src/app/shared/table-of-contents/index.ts, showcase/src/app/shared/table-of-contents/table-of-content-link.intf.ts, showcase/src/app/shared/table-of-contents/table-of-contents.component.html, showcase/src/app/shared/table-of-contents/table-of-contents.component.scss, showcase/src/app/shared/table-of-contents/table-of-contents.component.spec.ts, showcase/src/app/shared/table-of-contents/table-of-contents.component.ts, showcase/src/styles/_theme.scss, showcase/src/styles/styles.scss
ISSUES CLOSED: #720
```
[ ] Bugfix
[x] Feature
```
We need a getting started page to help new users to use Stark
Issue Number: #720 
A getting-started page has been created, along with a new table of content component, which might be used by other components as well in the future. 
```
[ ] Yes
[x] No
```
=> feat(stark-demo): creation of a getting started page

package.json
ISSUES CLOSED: #843
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #843
Commit messages from Greenkeeper customized as described here: https://greenkeeper.io/docs.html#custom-commit-messages
```
[ ] Yes
[X] No
```
=> style(stark-all): adapt commit messages from Greenkeeper to avoid any dependency upgrade to be shown as "bug fix"

package-lock.json, showcase/package-lock.json, starter/package-lock.json
```
[ ] Bugfix
[ ] Feature
```
Travis build failing due to some corrupted `package-lock.json` files causing this error:
```
npm ERR! import-fresh not accessible from husky:cosmiconfig
```
The corrupted `package-lock.json` files were re-generated.
```
[ ] Yes
[X] No
```
=> ci(build-main): re-create corrupted package-lock.json files from root, Showcase and Starter

package-lock.json, package.json, packages/stark-build/package-lock.json, packages/stark-core/package-lock.json, packages/stark-testing/package-lock.json, packages/stark-ui/package-lock.json, showcase/package-lock.json, starter/package-lock.json
Closes #863 
```
[ ] Bugfix
[ ] Feature
```
Current version: 0.67.1
Updated to the latest version: 0.67.3
```
[ ] Yes
[X] No
```
=> Greenkeeper/rollup 0.67.3

package-lock.json, package.json, packages/stark-build/package-lock.json, packages/stark-build/package.json, showcase/package-lock.json, showcase/package.json, starter/package-lock.json, starter/package.json
Closes #885
```
[ ] Bugfix
[ ] Feature
```
Current version: 7.0.6
Updated to the latest version: 7.1.0
```
[ ] Yes
[X] No
```
=> Greenkeeper/default/@angular/cli 7.1.0

package-lock.json, package.json, packages/stark-build/package-lock.json, packages/stark-build/package.json, packages/stark-ui/package-lock.json, packages/stark-ui/package.json
Closes #845 
```
[ ] Bugfix
[ ] Feature
```
Current version: 1.14.3
Updated to the latest version: 1.15.3
```
[ ] Yes
[X] No
```
=> Greenkeeper/default/prettier 1.15.3

packages/stark-build/config/webpack.dev.js
ISSUES CLOSED: #918
```
[X] Bugfix
[ ] Feature
```
Issue Number: #918 
The Showcase and the Starter apps run correctly on Internet Explorer 11 regardless on the platform where the DEV build was compiled.
```
[ ] Yes
[X] No
```
=> fix(stark-build): enhance regex for 3rd party libs to be transpiled to ES5 in Linux, Mac and Windows

docs/POLYFILLS.md, showcase/src/app/welcome/pages/getting-started/getting-started-page.component.html, showcase/src/app/welcome/pages/getting-started/getting-started-page.component.ts, showcase/src/app/welcome/pages/getting-started/starter-structure.ts
ISSUES CLOSED: #507 
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #507 
Documentation about the usage of polyfills.browsers.ts file has been added
```
[ ] Yes
[x] No
```
=> docs(docs): documentation about how to use polyfills.browser.ts

showcase/package-lock.json, showcase/package.json, starter/package-lock.json, starter/package.json
Closes #949
```
[ ] Bugfix
[ ] Feature
```
Current version: 7.0.0-beta.19
Updated to the latest version: 7.0.0-beta.21
```
[ ] Yes
[X] No
```
=> Greenkeeper/default/@angular/flex layout 7.0.0 beta.21

package-lock.json, package.json, packages/stark-build/package-lock.json, packages/stark-core/package-lock.json, packages/stark-testing/package-lock.json, packages/stark-ui/package-lock.json, showcase/package-lock.json, starter/package-lock.json
Closes #945 
```
[ ] Bugfix
[ ] Feature
```
Current version: 8.4.2
Updated to the latest version: 9.1.0
```
[ ] Yes
[x] No
```
=> Greenkeeper/release it 9.1.0

.cz-config.js, CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md
```
[ ] Bugfix
[ ] Feature
```
Some issues in the Readme, Code of Conduct and Contributing Guidelines (typos, wrong commands, obsolete/missing info)
- corrected Readme, Code of Conduct and Contributing Guidelines.
- re-formatted commit types in commitizen config file.
```
[ ] Yes
[ ] No
```
=> docs(stark-all): minor fixes in Readme, Code of Conduct and Contributing Guidelines

packages/stark-build/package-lock.json, packages/stark-build/package.json
Closes #978 
```
[ ] Bugfix
[ ] Feature
```
Current version: 2.0.0
Updated to the latest version: 3.0.1
```
[ ] Yes
[X] No
```
=> Greenkeeper/default/file loader 3.0.1

package-lock.json, package.json, packages/stark-build/config/webpack.common.js, packages/stark-core/src/modules/routing/services/routing.service.ts, packages/stark-core/src/modules/session.ts, packages/stark-core/src/modules/session/components/app-container.component.ts, packages/stark-core/src/modules/session/constants.ts, packages/stark-core/src/modules/session/routes.ts, packages/stark-core/src/modules/session/services/session.service.spec.ts, packages/stark-core/src/modules/session/services/session.service.ts, packages/stark-core/src/modules/session/session.module.ts, packages/stark-ui/package.json, packages/stark-ui/src/modules/table/components/table.component.spec.ts, packages/stark-ui/src/modules/table/components/table.component.ts
fix(stark-ui): fix table refresh issue when data changes.
fix(stark-build): ignore 'System.import()' messages due to @angular/core 
fix(stark-core): avoid circular dependencies by moving state names in a constants file
fix(stark-all): fix dependency issues in stark-ui + add hammerjs dep in stark root to fix warning during tests + improve stark-language-selector component
ISSUES CLOSED: #1003 #1004 
```
[X] Bugfix
[ ] Feature
```
Issue Number: #1003 #1004 
Issues are …
=> fix small bugs in stark-ui:table, stark-core:session and in stark-build 

package-lock.json, package.json
Closes #988 
```
[ ] Bugfix
[ ] Feature
```
Current version: 9.2.0
Updated to the latest version: 9.6.3
```
[ ] Yes
[X] No
```
=> Greenkeeper/release it 9.6.3

package-lock.json, package.json, packages/stark-build/package-lock.json, packages/stark-core/package-lock.json, packages/stark-testing/package-lock.json, packages/stark-ui/package-lock.json, showcase/package-lock.json, starter/package-lock.json
Closes #991 
```
[ ] Bugfix
[ ] Feature
```
Current version: 0.68.1
Updated to the latest version: 1.1.0
```
[ ] Yes
[X] No
```
=> Greenkeeper/rollup 1.1.0

package-lock.json, package.json, packages/stark-build/package-lock.json, packages/stark-build/package.json, showcase/package-lock.json, showcase/package.json, starter/package-lock.json, starter/package.json
Closes #1014 
```
[ ] Bugfix
[ ] Feature
```
Current version: 7.1.4
Updated to the latest version: 7.2.1
```
[ ] Yes
[X] No
```
=> Greenkeeper/default/@angular/cli 7.2.1

packages/stark-build/package-lock.json, packages/stark-build/package.json
Closes #1015 
```
[ ] Bugfix
[ ] Feature
```
Current version: 0.11.4
Updated to the latest version: 0.12.1
```
[ ] Yes
[X] No
```
=> Greenkeeper/default/@angular devkit/build angular 0.12.1

package-lock.json, packages/stark-build/package-lock.json, packages/stark-build/package.json, packages/stark-core/package-lock.json, packages/stark-testing/package-lock.json, packages/stark-ui/package-lock.json, showcase/package-lock.json, starter/package-lock.json
Closes #1016 
```
[ ] Bugfix
[ ] Feature
```
Current version: 0.11.4
Updated to the latest version: 0.12.1
```
[ ] Yes
[X] No
```
=> Greenkeeper/default/@angular devkit/build optimizer 0.12.1

package-lock.json, packages/stark-build/config/webpack.common.js, packages/stark-build/config/webpack.dev.js, packages/stark-build/config/webpack.prod.js, packages/stark-build/package-lock.json, packages/stark-build/package.json, packages/stark-core/package-lock.json, packages/stark-testing/package-lock.json, packages/stark-ui/package-lock.json, showcase/package-lock.json, starter/package-lock.json
Closes #926 
```
[ ] Bugfix
[ ] Feature
```
Current version: 1.0.1
Updated to the latest version: 2.1.0
```
[ ] Yes
[X] No
```
=> Greenkeeper/default/css loader 2.1.0

docs/POLYFILLS.md, packages/stark-ui/assets/styles/_material-fixes.scss, packages/stark-ui/assets/styles/_variables.scss, packages/stark-ui/assets/themes/_button-theme.scss, packages/stark-ui/assets/themes/_theming.scss, packages/stark-ui/src/modules/minimap/components/_minimap.component.scss, packages/stark-ui/src/modules/pagination/components/pagination.component.html, packages/stark-ui/src/modules/pagination/components/pagination.component.spec.ts, packages/stark-ui/src/modules/table/components/_table.component.scss, showcase/src/app/demo-ui/pages/message-pane/demo-message-pane-page.component.scss, showcase/src/app/demo-ui/pages/pretty-print/demo-pretty-print-page.component.html, showcase/src/app/styleguide/pages/typography/styleguide-typography-page.component.ts, showcase/src/polyfills.browser.ts, starter/src/polyfills.browser.ts
ISSUES CLOSED: #732 
```
[X] Bugfix
[ ] Feature
```
Issue Number: #732
Fixes several issues
```
[ ] Yes
[X] No
```
=> fix(stark-all): cross browser compatibility

package-lock.json, package.json
Closes #1031 
```
[ ] Bugfix
[ ] Feature
```
Current version: 7.1.2
Updated to the latest version: 7.3.1
```
[ ] Yes
[X] No
```
=> Greenkeeper/@commitlint/config conventional 7.3.1

package-lock.json, package.json
Closes #1035 
```
[ ] Bugfix
[ ] Feature
```
Current version: 9.7.1
Updated to the latest version: 9.8.1
```
[ ] Yes
[X] No
```
=> Greenkeeper/release it 9.8.1

build.sh
- Before this commit the error "unbound variable" was thrown from several places when trying to build a single package on macOS. Eg:  `npm run build:stark-ui`
- fix small code warnings
ISSUES CLOSED: #1059
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #1059 
```
[ ] Yes
[x] No
```
Please test on windows before merging. 😄
=> build(build-main): fix build on macOS

showcase/angular.json, showcase/config/index-head-config.js, showcase/src/index.html, starter/angular.json, starter/config/index-head-config.js, starter/src/index.html
add stylesheet link through webpack instead of directly into `index.html`
ISSUES CLOSED: #1037
```
[x] Bugfix
[ ] Feature
```
Issue Number:  #1037
```
[ ] Yes
[x] No
```
=> fix(stark-demo): fix 404 error when loading `pre-load-style.css`

greenkeeper.json
```
[ ] Bugfix
[ ] Feature
```
The current greenkeeper config file ignores some libraries that should also be upgraded (since this PR was merged: https://github.com/NationalBankBelgium/stark/pull/1079).
- Removed some ignored libraries that should also be upgraded
- Split the packages into 2 categories: stark-packages and stark-apps so that Greenkeeper creates more meaningful PRs.
```
[ ] Yes
[X] No
```
=> chore(stark-all): adapt greenkeeper.json file to restructure the packages and remove previously ignored libs

packages/stark-ui/src/modules/progress-indicator/testing.ts, packages/stark-ui/src/modules/progress-indicator/testing/progress-indicator.mock.ts, packages/stark-ui/testing/public_api.ts
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe:
```
There is no mock implementation for the new progress-indicator service.
A mock implementation for the service has been added.
```
[ ] Yes
[X] No
```
=> test(stark-ui): add missing mock implementation for progress indicator service

packages/stark-ui/src/modules/app-sidebar/services.ts, packages/stark-ui/src/modules/message-pane/services.ts, packages/stark-ui/src/modules/progress-indicator/services.ts, packages/stark-ui/src/modules/toast-notification/services.ts, packages/stark-ui/src/modules/toast-notification/testing/toast-notification.mock.ts
ISSUES CLOSED: #1112
```
[ ] Bugfix
[X] Feature
```
Issue Number: #1112
Refined exports in the services.
```
[ ] Yes
[X] No
```
=> feat(stark-all): refine exports for the services

packages/stark-ui/package.json, packages/stark-ui/src/common/message.ts
```
[X] Bugfix
[ ] Feature
```
There is a missing export in stark-ui for StarkMessageImpl and there is a missing peerDependency in `package.json`.
Missing export and peerDeps have been added.
```
[ ] Yes
[X] No
```
=> fix(stark-ui): fix minor issues in stark-ui

starter/angular.json
```
[x] Bugfix
[ ] Feature
```
The build of starter was breaking because of an invalid import added to the angular.json file.
Removed the import, build is succeeding again.
```
[ ] Yes
[x] No
```
=> fix(stark-starter): remove faulty import from angular.json

showcase/ghpages-adapt-bundle-urls.js
```
[X] Bugfix
[ ] Feature
```
Some assets in the deployed Showcase app on GhPages have a wrong URL as mentioned in #1036 due to some placeholders `<stark-dummy-base-href>` and `<stark-dummy-deploy-url>` not being replaced with the actual baseHref and deployURL and also duplication of the baseHref and deployURL.
- The script to replace the placholders for the actual baseHref and deployUrl is adapted to fix the issue about some placeholders `<stark-dummy-base-href>` and …
=> fix(stark-demo): minor fixes in script that replaces baseHref and deployURL in Showcase when deploying to GhPages

showcase/src/app/shared/components/table-of-contents/table-of-contents.component.scss
ISSUES CLOSED: #1137
```
[x] Bugfix
[ ] Feature
```
Issue Number:  #1137
removed transform property from `table-of-contents` component.
```
[ ] Yes
[x] No
```
=> fix(stark-demo): remove transform from `table-of-contents` component

gh-deploy.sh
ISSUES CLOSED: #1138
```
[X] Bugfix
[ ] Feature
```
Issue Number: #1138 
The `latest` folders from API docs and Showcase are deleted and re-created before copying the new files to ensure that they contain only the new content.
```
[ ] Yes
[X] No
```
=> fix(release): remove all files from 'latest' folders before copying the new ones

packages/stark-core/src/modules/user/repository/user.repository.ts, packages/stark-core/src/validation/validator.ts, packages/stark-ui/src/modules/app-sidebar/services/app-sidebar.service.ts, packages/stark-ui/src/modules/progress-indicator/directives/progress-indicator.directive.ts, packages/stark-ui/src/modules/progress-indicator/services/progress-indicator.service.ts, packages/stark-ui/src/modules/table/components/column.component.ts, packages/stark-ui/src/modules/toast-notification/services/toast-notification.service.ts
```
[ ] Bugfix
[ ] Feature
```
After the automatic upgrade of TSLint to v5.13.0, some new violations were reported which break the Travis build.
The new violations are fixed. They were already there but the previous versions of TSLint didn't detect them correctly.
```
[ ] Yes
[X] No
```
=> chore(stark-all): fix new linting violations after TSLint upgrade to 5.13.0

docs/stark-ui/GENERIC_SEARCH.md, docs/stark-ui/TIMEOUT_WARNING.md, showcase/src/app/app-menu.config.ts, showcase/src/app/demo-ui/pages/footer/demo-footer-page.component.html, showcase/src/app/demo-ui/pages/generic-search/demo-generic-search-page.component.ts, showcase/src/app/demo-ui/pages/minimap/demo-minimap-page.component.html, showcase/src/app/demo-ui/pages/route-search/demo-route-search-page.component.html, showcase/src/app/demo-ui/pages/route-search/demo-route-search-page.component.ts, showcase/src/app/demo-ui/routes.ts, showcase/src/app/styleguide/routes.ts, showcase/src/assets/translations/en.json, showcase/src/assets/translations/fr.json, showcase/src/assets/translations/nl.json
```
[ ] Bugfix
[ ] Feature
```
Inconsistent translations and titles in menu and demo pages.
- Adapted translations to keep consistency in the different languages.
- Order the menu options alphabetically.
- Adapted some demo pages to keep consistency.
- Added missing content in some MD files.
```
[ ] Yes
[X] No
```
=> chore(stark-demo): minor fixes: translations, order entries alphabetically in menu

packages/stark-ui/package-lock.json, packages/stark-ui/package.json, showcase/package-lock.json
Closes #1122
```
[ ] Bugfix
[ ] Feature
```
Current version: 12.1.0
Updated to the latest version: 13.1.1
```
[ ] Yes
[X] No
```
=> Greenkeeper/stark packages/nouislider 13.1.1

packages/stark-ui/base.spec.ts, packages/stark-ui/src/modules/date-picker/components/date-picker.component.spec.ts, packages/stark-ui/src/modules/date-range-picker/components/date-range-picker.component.spec.ts, packages/stark-ui/src/modules/keyboard-directives/directives/restrict-input.directive.spec.ts, packages/stark-ui/src/modules/pagination/components/pagination.component.spec.ts, packages/stark-ui/src/modules/table/components/table.component.spec.ts, showcase/base.spec.ts, starter/base.spec.ts
```
[ ] Bugfix
[ ] Feature
```
Some unit tests not working on Firefox, Edge and IE due to some vendor specific API inconsistencies in such browsers.
All unit tests working in major browsers: Chrome, Firefox, Edge and IE.
```
[ ] Yes
[X] No
```
=> refactor(stark-ui): adapt unit tests to make them cross-browser compatible

packages/stark-ui/src/modules/pagination/components/pagination.component.html, packages/stark-ui/src/modules/table/components/table.component.html, packages/stark-ui/src/modules/table/components/table.component.spec.ts, packages/stark-ui/src/modules/table/components/table.component.ts, showcase/src/app/demo-ui/components/table-with-custom-actions/table-with-custom-actions.component.html, showcase/src/app/demo-ui/components/table-with-custom-actions/table-with-custom-actions.component.ts, showcase/src/app/demo-ui/components/table-with-custom-styling/table-with-custom-styling.component.html, showcase/src/app/demo-ui/components/table-with-custom-styling/table-with-custom-styling.component.ts, showcase/src/app/demo-ui/components/table-with-fixed-actions/table-with-fixed-actions.component.html, showcase/src/app/demo-ui/components/table-with-fixed-actions/table-with-fixed-actions.component.ts, showcase/src/app/demo-ui/components/table-with-fixed-header/table-with-fixed-header.component.html, showcase/src/app/demo-ui/components/table-with-fixed-header/table-with-fixed-header.component.ts, showcase/src/app/demo-ui/components/table-with-selection/table-with-selection.component.html, showcase/src/app/demo-ui/components/table-with-selection/table-with-selection.ts, showcase/src/app/demo-ui/components/table-with-transcluded-action-bar/table-with-transcluded-action-bar.component.html, showcase/src/app/demo-ui/components/table-with-transcluded-action-bar/table-with-transcluded-action-bar.component.ts, showcase/src/assets/examples/table/regular/table.scss, showcase/src/assets/examples/table/regular/table.ts, showcase/src/assets/examples/table/with-custom-actions/table.html, showcase/src/assets/examples/table/with-custom-actions/table.ts, showcase/src/assets/examples/table/with-custom-styling/table.html, showcase/src/assets/examples/table/with-custom-styling/table.ts, showcase/src/assets/examples/table/with-fixed-actions/table.html, showcase/src/assets/examples/table/with-fixed-actions/table.ts, showcase/src/assets/examples/table/with-fixed-header/table.html, showcase/src/assets/examples/table/with-fixed-header/table.ts, showcase/src/assets/examples/table/with-selection/table.html, showcase/src/assets/examples/table/with-selection/table.ts, showcase/src/assets/examples/table/with-transcluded-action-bar/table.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1090 #1012
Table pagination has default and keeps in sync with the (filtered) data
```
[ ] Yes
[x] No
```
=> fix(stark-ui): fix Table pagination config issues. Adapt demos in showcase

LICENSE, packages/license-banner.txt
=> docs: update license year

packages/stark-core/src/modules/http/repository/http-abstract-repository.spec.ts, packages/stark-core/src/modules/logging/services/logging.service.spec.ts, packages/stark-core/src/modules/routing/services/routing.service.intf.ts, packages/stark-core/src/modules/routing/services/routing.service.spec.ts, packages/stark-core/src/modules/routing/services/routing.service.ts, packages/stark-core/src/modules/session/services/session.service.spec.ts, packages/stark-core/src/modules/settings/effects/settings.effects.spec.ts, packages/stark-core/src/modules/xsrf/services/xsrf.service.spec.ts, packages/stark-testing/package-lock.json, packages/stark-testing/package.json, packages/stark-ui/src/modules/app-sidebar/components/app-sidebar.component.spec.ts, packages/stark-ui/src/modules/app-sidebar/components/app-sidebar.component.ts, packages/stark-ui/src/modules/breadcrumb/components/breadcrumb.component.spec.ts, packages/stark-ui/src/modules/breadcrumb/components/breadcrumb.component.ts, packages/stark-ui/src/modules/generic-search/classes/abstract-search-component.spec.ts, packages/stark-ui/src/modules/progress-indicator/reducers/progress-indicator.reducer.ts, packages/stark-ui/src/modules/progress-indicator/services/progress-indicator.service.spec.ts, packages/stark-ui/src/modules/session-ui/effects/session-timeout-warning.effect.spec.ts, packages/stark-ui/src/modules/table/components/table.component.spec.ts
```
[X] Bugfix
[ ] Feature
```
After the automatic upgrade of `@types/jasmine` to v3.3.12, some new violations were reported on our `.spec.ts` files which break the Travis build.
- The new violations are fixed.
- Adapted the `package.json` file in stark-testing to specify the latest version of `@types/jasmine` being used.
```
[ ] Yes
[X] No
```
=> test(stark-all): fix TSLint errors in unit tests after upgrade of @types/jasmine to v3.3.12

packages/stark-ui/package-lock.json, packages/stark-ui/package.json, packages/stark-ui/src/modules/pretty-print/components/pretty-print.component.ts
```
[ ] Bugfix
[ ] Feature
```
After the automatic upgrade of `@types/prismjs`, the PrismJS related code in the `StarkPrettyPrint`component has some TSC compilation errors.
The code has been adapted to align with the latest version of `@types/prismjs`.
```
[ ] Yes
[X] No
```
=> Greenkeeper/stark packages/@types/prismjs 1.16.0

packages/stark-ui/src/modules/collapsible/components/_collapsible.component.scss, packages/stark-ui/src/modules/collapsible/components/collapsible.component.html, packages/stark-ui/src/modules/collapsible/components/collapsible.component.spec.ts, packages/stark-ui/src/modules/collapsible/components/collapsible.component.ts, showcase/src/app/demo-ui/pages/collapsible/demo-collapsible-page.component.html, showcase/src/app/demo-ui/pages/collapsible/demo-collapsible-page.component.ts, showcase/src/assets/examples/collapsible/collapsible-custom.html, showcase/src/assets/examples/collapsible/collapsible-custom.ts, showcase/src/assets/examples/collapsible/collapsible-default.ts
- rotate the default icon by 90deg when the collapsible is open
- small refactor
ISSUES CLOSED: #1013
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(stark-demo): change default behaviour of collapsible icon

packages/stark-ui/src/modules/collapsible/components/collapsible.component.html, showcase/src/app/demo-ui/pages/dropdown/demo-dropdown-page.component.ts
```
[X] Bugfix
[ ] Feature
```
There is an error message due to `'unsubcribe' called on undefined` in dropdown demo-page.
There is also a missing a BREAKING CHANGE in our history.
I fixed the issue in the demo page.
I added a small commit with the missing message.
```
[ ] Yes
[X] No
```
=> Bugfix/fix dropdown demo issue + Add missing commit message for CHANGELOG

check-stark-versions.js
```
[X] Bugfix
[ ] Feature
```
After the implementation of Stark RBAC package via #1215 the script to check the versions of stark packages in the `package.json` of Starter fails with the following error:
```
Version of package stark-rbac is not correct. It should be 'latest'
```
However the `stark-rbac` package is not part of the dependencies of the Starter.
The script has been adapted to only check the versions of those packages that are actually listed as …
=> fix(release): enhance check for stark versions in Starter to skip those packages that are not listed as dependencies

packages/rollup.config.common-data.js, packages/stark-ui/karma.conf.js, packages/stark-ui/src/modules/table/components/table.component.spec.ts, packages/stark-ui/src/modules/table/components/table.component.ts
ISSUES CLOSED: #1241
```
[X] Bugfix
[ ] Feature
```
Cannot change sorting in the Table component.
Issue Number: #1241 
It's working 😃 
```
[ ] Yes
[X] No
```
=> fix(stark-ui): table - fix sorting + fix onChanges on columnProperties

packages/stark-ui/src/modules/progress-indicator/actions/progress-indicator.actions.ts, packages/stark-ui/src/modules/progress-indicator/components/progress-indicator.component.html, packages/stark-ui/src/modules/progress-indicator/components/progress-indicator.component.spec.ts, packages/stark-ui/src/modules/progress-indicator/components/progress-indicator.component.ts, packages/stark-ui/src/modules/progress-indicator/directives/progress-indicator.directive.spec.ts, packages/stark-ui/src/modules/progress-indicator/directives/progress-indicator.directive.ts, packages/stark-ui/src/modules/progress-indicator/entities.ts, packages/stark-ui/src/modules/progress-indicator/entities/progress-indicator-config.entity.intf.ts, packages/stark-ui/src/modules/progress-indicator/entities/progress-indicator-full-config.entity.intf.ts, packages/stark-ui/src/modules/progress-indicator/entities/progress-indicator-full-config.entity.ts, packages/stark-ui/src/modules/progress-indicator/entities/progress-indicator-type.entity.ts, packages/stark-ui/src/modules/progress-indicator/reducers/index.ts, packages/stark-ui/src/modules/progress-indicator/reducers/progress-indicator.reducer.spec.ts, packages/stark-ui/src/modules/progress-indicator/reducers/progress-indicator.reducer.ts, packages/stark-ui/src/modules/progress-indicator/services/progress-indicator.service.intf.ts, packages/stark-ui/src/modules/progress-indicator/services/progress-indicator.service.spec.ts, packages/stark-ui/src/modules/progress-indicator/services/progress-indicator.service.ts
```
[X] Bugfix
[ ] Feature
```
After the changes done in #1218, there is a regression in the `StarkProgressIndicatorDirective`: the spinner is not shown anymore.
- fixed the faulty code causing the issue
- refactored the directive to simplify the logic to show/hide the spinner (no API changes)
- as a result of this simplification, the `StarkProgressIndicatorComponent` has also been simplified.
- expand the unit tests to cover all scenarios
- move some properties that …
=> fix(stark-ui): fix regression in ProgressIndicator directive introduced in #1218

starter/package.json
Closes #1265
```
[ ] Bugfix
[ ] Feature
```
Current version: 1.3.1
Updated to the latest version: 2.1.0
```
[ ] Yes
[X] No
```
=> chore(package): update husky to version 2.1.0

package-lock.json, package.json
Closes #1264 
```
[ ] Bugfix
[ ] Feature
```
Current version: 1.3.1
Updated to the latest version: 2.1.0
```
[ ] Yes
[X] No
```
=> Greenkeeper/stark packages/husky 2.1.0

.travis.yml
```
[X] Bugfix
[ ] Feature
```
The current configuration of Travis doesn't trigger builds if we release an RC version.
RC tags trigger Travis builds
```
[ ] Yes
[X] No
```
=> fix(build-main): fix travis branches (before alpha/beta, now alpha/beta/rc)

packages/stark-ui/src/modules/table/components/table.component.html, packages/stark-ui/src/modules/table/components/table.component.spec.ts, packages/stark-ui/src/modules/table/components/table.component.ts, showcase/src/app/demo-ui/components/table-regular/table-regular.component.html, showcase/src/assets/examples/table/regular/table.html
ISSUES CLOSED: #1283
```
[ ] Bugfix
[X] Feature
```
Issue Number: #1283 
Provide a row index.
```
[ ] Yes
[X] No
```
=> fix(stark-ui): table - add row index option

package-lock.json, packages/stark-build/package-lock.json, showcase/package-lock.json
```
[ ] Bugfix
[ ] Feature
```
Github reports security vulnerabilities in these dependencies:
- [tar](https://nvd.nist.gov/vuln/detail/CVE-2018-20834)
- fstream ([see vulnerability fix](https://github.com/npm/fstream/commit/6a77d2fa6e1462693cf8e46f930da96ec1b0bb22))
Affected deps bumped to the patched versions.
```
[ ] Yes
[X] No
```
=> chore(stark-all): re-generate package-lock.json files to bump deps with security vulnerabilities

starter/package.json
Closes #1342
```
[ ] Bugfix
[ ] Feature
```
Current version: 2.4.1
Updated to the latest version: 2.7.0
According to the CHANGELOG of this library:
>Due to issues with Git < 2.13.2, this version is a rollback and is the same as husky v2.4.1. Changes introduced in v2.5.0 and v2.6.0 will be published in v3.0.0.
```
[ ] Yes
[X] No
```
=> chore(package): update husky to version 2.7.0

packages/stark-ui/src/modules/dropdown/components/dropdown.component.html, packages/stark-ui/src/modules/dropdown/components/dropdown.component.ts
ISSUES CLOSED: #1369, #1370
```
[X] Bugfix
[ ] Feature
```
See related issues.
Issue Number: #1369, #1370
Issues fixed.
```
[ ] Yes
[X] No
```
=> fix(stark-ui): dropdown - fix container click + badly floating label in multiSelect

packages/stark-ui/src/modules/app-sidebar/components/_app-sidebar.component.scss, showcase/src/app/app.component.html, starter/src/app/app.component.html
A fixed header placed in the sidenav-content node was causing an issue in Safari.
ISSUES CLOSED: #1338
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1338 
Issue fixed
```
[ ] Yes
[x] No
```
=> fix(stark-demo): move header outside of sidenav-content

showcase/package-lock.json, showcase/package.json, starter/package.json
Closes #1378 
```
[ ] Bugfix
[ ] Feature
```
Current version: 3.1.2
Updated to the latest version: 3.2.1
```
[ ] Yes
[X] No
```
=> Greenkeeper/stark apps/core js 3.2.1

package-lock.json, package.json
Closes #1348
```
[ ] Bugfix
[ ] Feature
```
Current version: 8.1.0
Updated to the latest version: 9.2.1
```
[ ] Yes
[X] No
```
=> Greenkeeper/stark packages/lint staged 9.2.1

showcase/package-lock.json, showcase/package.json, starter/package.json
Closes #1349
```
[ ] Bugfix
[ ] Feature
```
Current version: 8.1.0
Updated to the latest version: 9.2.1
```
[ ] Yes
[X] No
```
=> Greenkeeper/stark apps/lint staged 9.2.1

packages/stark-ui/assets/styles/_base.scss, showcase/src/app/app.component.html, starter/src/app/app.component.html
```
[x] Bugfix
[ ] Feature
```
Because of a bug previously introduced in a previous commit the side navigations (left / right) were rendering behind the header, causing issues on mobile or whenever the side navigation has full page height.
This commit fixes the initial Safari bug (#1338) without breaking the side navigation.
```
[ ] Yes
[x] No
```
=> fix(stark-ui): fix side navigation rendering behind header

showcase/package-lock.json, showcase/package.json, starter/package.json
Closes #1400 
```
[ ] Bugfix
[ ] Feature
```
Current version: 9.2.5
Updated to the latest version: 9.4.0
```
[ ] Yes
[X] No
```
=> Greenkeeper/stark apps/lint staged 9.4.0

README.md
ISSUES CLOSED: #1387
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1387 
display the correct BrowserStack badge in `README.md`
```
[ ] Yes
[x] No
```
=> fix(docs): update BrowserStack badge to display correctly from `README.md`

packages/stark-build/package-lock.json, packages/stark-build/package.json
Closes #1411 
```
[ ] Bugfix
[ ] Feature
```
Current version: 0.10.5
Updated to the latest version: 1.0.1
```
[ ] Yes
[X] No
```
=> Greenkeeper/stark packages/stylelint webpack plugin 1.0.1

showcase/README.md, starter/README.md
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #1414 
Fixed typos in `git clone` commands of the Starter and Showcase.
```
[ ] Yes
[ ] No
```
=> docs: fix typo in 'git clone' command in README of Starter and Showcase

packages/stark-ui/src/modules/pagination/components/_pagination.component.scss
ISSUES CLOSED: #1345
```
[X] Bugfix
[ ] Feature
```
Issue Number: #1345 
The "items per page" selected value is now visible again.
```
[ ] Yes
[X] No
```
=> fix(stark-ui): fix missing width in the "items per page" dropdown of StarkPagination component

showcase/package-lock.json, showcase/package.json, starter/package.json
Closes #1416
```
[ ] Bugfix
[ ] Feature
```
Current version: 3.2.1
Updated to the latest version: 3.4.0
```
[ ] Yes
[X] No
```
=> Greenkeeper/stark apps/core js 3.4.0

showcase/package-lock.json, showcase/package.json, starter/package.json
Closes #1433 
```
[ ] Bugfix
[ ] Feature
```
Current version: 8.4.1
Updated to the latest version: 8.5.2
```
[ ] Yes
[X] No
```
=> Greenkeeper/stark apps/ts node 8.5.2

packages/stark-ui/src/modules/table/components/column.component.html, packages/stark-ui/src/modules/table/components/column.component.ts, packages/stark-ui/src/modules/table/components/table.component.spec.ts, packages/stark-ui/src/modules/table/components/table.component.ts, packages/stark-ui/src/modules/table/entities.ts, packages/stark-ui/src/modules/table/entities/column-cell-clicked-output.intf.ts, showcase/src/app/demo-ui/components/table-regular/table-regular.component.ts, showcase/src/assets/examples/table/regular/table.ts
ISSUES CLOSED: #1466
```
[X] Bugfix
[X] Feature
```
Cell click not handled.
Issue Number: #1466 
Cell click is now handled.
```
[ ] Yes
[X] No
```
=> fix(stark-ui): add support for `onClickCallback` column properties in Table component

showcase/src/app/app.module.ts, showcase/src/app/router.config.ts, showcase/src/main.browser.ts, showcase/src/polyfills.browser.ts, starter/src/app/app.module.ts, starter/src/app/router.config.ts, starter/src/main.browser.ts, starter/src/polyfills.browser.ts
```
[ ] Bugfix
[X] Feature
```
All the logs displayed in 'dev' mode in the showcase are also displayed in the 'prod' build.
Since we are going to release our final release, we should have a clean console without all those logs.
Almost no logs in 'production' build of the "showcase" and the "starter".
```
[ ] Yes
[X] No
```
=> showcase/starter: stop dev logging in 'production' mode

docs/stark-rbac/TESTING_SUBPACKAGE.md, docs/stark-rbac/summary.json, packages/stark-rbac/.compodocrc.json, packages/stark-rbac/README.md, packages/stark-rbac/package.json, packages/stark-rbac/src/modules/authorization/actions/authorization.actions.ts, packages/stark-rbac/src/modules/authorization/authorization.module.ts, packages/stark-rbac/src/modules/authorization/directives/hide-on-permission.directive.ts, packages/stark-rbac/src/modules/authorization/directives/show-on-permission.directive.ts, packages/stark-rbac/src/modules/authorization/entities/state-permissions.entity.intf.ts, packages/stark-rbac/src/modules/authorization/entities/state-redirection.intf.ts, packages/stark-rbac/src/modules/authorization/services/authorization.service.intf.ts, packages/stark-rbac/testing/README.md, packages/stark-rbac/testing/src/authorization.mock.md, packages/stark-rbac/testing/src/authorization.mock.ts
```
[X] Bugfix
[X] Feature
```
Issue Number: #1600 
The docs of the testing subpackage from the Stark-RBAC are now generated and included in the Stark API Docs.
```
[ ] Yes
[X] No
```
Took the chance to do some minor fixes/corrections to the existing documentation 👍
=> Feature/docs stark-rbac testing subpackage

showcase/src/index.html, starter/src/index.html
fix typo in 2 links rel
ISSUES CLOSED: #1971 
```
[x] Bugfix
[ ] Feature
```
typo noopenenr
Issue Number: #1971 
fix noopener
```
[ ] Yes
[x] No
```
=> fix typo in links rel, showcase + starter 

packages/stark-ui/src/modules/table/components/_table.component.scss, packages/stark-ui/src/modules/table/components/table.component.html, packages/stark-ui/src/modules/table/components/table.component.spec.ts, packages/stark-ui/src/modules/table/components/table.component.ts, packages/stark-ui/src/modules/table/directives/table-expand-detail.directive.ts, packages/stark-ui/src/modules/table/table.module.ts, showcase/src/app/demo-ui/components/index.ts, showcase/src/app/demo-ui/components/table-with-collapsible-rows/index.ts, showcase/src/app/demo-ui/components/table-with-collapsible-rows/table-with-collapsible-rows.component.html, showcase/src/app/demo-ui/components/table-with-collapsible-rows/table-with-collapsible-rows.component.scss, showcase/src/app/demo-ui/components/table-with-collapsible-rows/table-with-collapsible-rows.component.ts, showcase/src/app/demo-ui/demo-ui.module.ts, showcase/src/app/demo-ui/pages/table/demo-table-page.component.html, showcase/src/assets/examples/table/with-collapsible-rows/index.ts, showcase/src/assets/examples/table/with-collapsible-rows/table.html, showcase/src/assets/examples/table/with-collapsible-rows/table.scss, showcase/src/assets/examples/table/with-collapsible-rows/table.ts, showcase/src/assets/translations/en.json, showcase/src/assets/translations/fr.json, showcase/src/assets/translations/nl.json
Closes #1637
```
[ ] Bugfix
[x] Feature
```
Issue Number: #1637
Adding the option to collapse table rows
```
[ ] Yes
[x] No
```
=> feat(stark-ui): added collapsible table rows

.github/workflows/build.yml
Replacing classic regex by a pattern supported by GH Actions
ISSUE CLOSED: #2870
```
[X] Bugfix
[ ] Feature
```
No CI for Pull Request regarding 10.2.x branch
CI should be triggered
```
[ ] Yes
[X] No
```
=> ci(build-main): fix branches pattern in GH workflow configuration

.github/workflows/build.yml
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> ci(build-main): fix pattern of workflow trigger event

packages/stark-build/config/webpack-partial.dev.js
ISSUES CLOSED: #3086
```
[X] Bugfix
[ ] Feature
```
Issue Number: #3086
No more warning/error
```
[ ] Yes
[X] No
```
=> fix(stark-build): remove csp 'plugin-types' rule and adapt 'object-src' rule

packages/stark-ui/src/modules/restrict-input-directive/directives/restrict-input.directive.spec.ts, packages/stark-ui/src/modules/restrict-input-directive/directives/restrict-input.directive.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1905
Drop event and paste event are handle to validate the values
```
[ ] Yes
[X] No
```
=> fix(stark-ui): handles paste and drop event on the restrict-input directive

packages/stark-core/src/modules/logging/services/logging.service.ts
ISSUES CLOSED: #3620
```
[X] Bugfix
[ ] Feature
```
Issue Number: #3620
The correlation-id is now generated even when the loggingFlush is disabled.
```
[ ] Yes
[X] No
```
=> fix(stark-core): enable correlation-id generation when `loggingFlushDisabled == true`

packages/stark-core/src/modules/http/services/http.service.ts
Because the end of support IE we could removed specific code for IE.
ISSUES CLOSED: #3636
```
[ ] Bugfix
[x] Feature
```
Issue Number:  #3636 
```
[x] Yes
[ ] No
```
=> feat(stark-core): removed Throw Error to create stack trace for IE

.github/workflows/build.yml
ISSUES RELATED: #3697
```
[X] Bugfix
[ ] Feature
```
CI is broken.
Issue Number: #3697 
Disable tests in BrowserStack in order to fix CI.
```
[ ] Yes
[X] No
```
=> ci(build-main): temporary disable tests executed in BrowserStack

.github/workflows/build.yml, .prettierignore
add exclusions in .prettierignore file
```
[ ] Bugfix
[ ] Feature
```
When there is a formatting issue in a pull request, no error is triggered in the CI.
If a file can be formatted by `prettier`, the CI will trigger an error.
```
[ ] Yes
[X] No
```
=> ci(build-main): add `prettier` check in build.yml GitHub workflow

packages/stark-core/src/modules/routing/services/routing.service.spec.ts, packages/stark-core/src/modules/routing/services/routing.service.ts
ISSUE CLOSED: #3766
```
[X] Bugfix
[ ] Feature
```
Issue Number: #3766
Query params in URL are handled correctly.
```
[ ] Yes
[X] No
```
=> fix(stark-core): fix support for URL query parameters

.github/workflows/build.yml, .github/workflows/bump-angular-deps.yml, .github/workflows/dependabot-sync-stark-dependencies.yml
Following Actions have been updated:
- `actions/cache`: v2 -> v4
- `actions/checkout`: v2 -> v4
- `actions/setup-node`: v2 -> v4
- `actions/download-artifact`: v2 -> v3
- `actions/upload-artifact`: v2 -> v3
- `peter-evans/create-pull-request`: v3 -> v6
```
[ ] Bugfix
[ ] Feature
```
GitHub Actions used in workflows are outdated.
GitHub Actions are updated.
```
[ ] Yes
[X] No
```
=> ci(build-main): update GitHub Actions used in ".github/workflows"

docs/MIGRATION-ESLINT.md, docs/MIGRATION_ANGULAR_13.md, docs/MIGRATION_ANGULAR_14.md, docs/MIGRATION_ANGULAR_15.md, docs/MIGRATION_ANGULAR_16.md, docs/MIGRATION_GUIDE_STARK_12.md
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Documentation for migration
```
```
[ ] Yes
[X] No
```
=> feat(docs): add documentation to upgrade from Stark 10 (Angular 7) to Stark 12 (Angular 16)

docs/MIGRATION_ANGULAR_13.md, docs/MIGRATION_ANGULAR_14.md, docs/MIGRATION_ANGULAR_15.md, docs/MIGRATION_ANGULAR_16.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> docs(stark-all): update migration guide to include versions for "@nationalbankbelgium/ngx-form-errors"

docs/MIGRATION_ANGULAR_16.md
```
[ ] Bugfix
[ ] Feature
```
Update migration guide for stark
```
[ ] Yes
[x] No
```
=> docs(release): update stark version in Angular 16 migration guide

.github/workflows/build.yml
Reformat build.yml file thanks to Prettier.
Update `artifact` actions due to deprecation notice: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
```
[ ] Bugfix
[ ] Feature
```
GH Workflow is using a deprecated action (upload-artifact@v2) which is deprecated.
More details on: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
GH Actions in build.yml workflow are up-to-date. …
=> ci(build-main): update Actions in GitHub workflow
